### ISSUE TITLE
new product creation in admin-ui

### ISSUE THREAD

**Issue by werkzeugh** [vendure-ecommerce/vendure#102]
**Describe the bug**
 new products  w/o variants dont show up in "products"

**To Reproduce**

❖  create a product in admin-ui:
• click "new product"
• fill out only product name, click"create"
❖ go to "Products",  new product is not listed
❖ it works, when creating a product-variant

**Expected behavior**

"products" should list the created product

either create a product variant by default,
list products w/o variants as well,

**Environment (please complete the following information):**
- @vendure/core version: 0.1.2-beta.2
- Nodejs version: 10.13.0
- Database (mysql/postgres etc): mariadb 10.2.8

**Comment by michaelbromley** [comment]
This is a tricky one, since the search index is only aware of ProductVariants and not Products. Creating a default variant might be the solution. 

I am planning on re-visiting the whole process of product creation (there are a couple of aspects I am not happy with), so I will address this issue at that point.

**Comment by michaelbromley** [comment]
Fixed by #127
