### ISSUE TITLE
Admin UI requests to the API always have `?languageCode=en` (no way to change default language)

### ISSUE THREAD

**Issue by skid** [vendure-ecommerce/vendure#1033]
**Describe the bug**
Basically, the default language is fixed to english and there is no way to change it. This causes all kinds of problems. For example, if you remove english as a language and use another default language, entities are created with the EN language since it's read from the request context.

**To Reproduce**
1. Create a fresh Vendure project and set `defaultLanguageCode` to e.g. 'mk' (just to show it has no effect)
2. Add a new language (e.g. 'mk'), set it as the default channel's default language
3. Remove english as a language
4. Log into the Admin UI and inspect the requests

**Expected behavior**
I don't know. Probably the `languageCode` graphql parameter to be equal to the selected default language - in case there is a single language defined which is not "en" - set it to that.

**Environment (please complete the following information):**
 - @vendure/core version: 1.1.3

**Comment by skid** [comment]
While doing some digging, I noticed that `http://localhost:3000/admin/vendure-ui-config.json` returns `defaultLanguage` as `en`

**Comment by michaelbromley** [comment]
Thanks for the report. Just looked into this and here's what's going on:

* There is a local state variable,  `uiState.contentLanguage`. This is responsible for setting the `languageCode=xx` query parameter. By default it is set to the value of the `defaultlanguage` property of the AdminUiConfig object (which is `en` by default).
* The value of the `uiState.contentLanguage` variable is updated whenever you set the content language using the language dropdown: 
![image](https://user-images.githubusercontent.com/6275952/129962262-2b0e8620-f067-4ef6-9b3a-ed8e756a2bff.png)
* However, this language dropdown is only displayed if there is more than 1 language set up in GlobalSettings.
* So in the repro steps you describe above, you end up in the situation where, even though MK has been set as the default and only language, the `uiState.contentLanguage` var never got updated because at no point was the language dropdown changed to MK (because it is invisible since there is only 1 defined language in GlobalSettings).

To illustrate this, you can try adding EN to the GlobalSettings language list. Then go to the product list and select MK. Inspect the network tab and observe that now the `languageCode=mk` query param is appended to all requests.

So the solution needs to include some logic to detect this case, where there is a single language defined and that language differs from what is currently set in `uiState.contentLanguage`. Probably this can be done in the GlobalSettingsComponent, as a check after calling the `save()` method.
