### ISSUE TITLE
Slug uniqueness is not enforced cross-language

### ISSUE THREAD

**Issue by coderjib** [vendure-ecommerce/vendure#1044]
**Describe the bug**
The system doesn't allow to create a second product with the same slug, but that is not true if the second time you use a different language.
When you have 2 products with the same slug, even if in different languages, the consequence I have seen repeatedly is that none of them is ever displayed in results of search queries, i.e. they seem to be ignored. To solve you need to erase the second product translation and re-index...

**To Reproduce**
1. Create a new product from the panel with the default language with the slug 'abc'
2. Now try to do the same: the product is saved, but the slug is automatically changed to 'abc-2'
3. Now from the product panel switch to the second language and try to create the same product
4. See the product saved

**Expected behavior**
Slug uniqueness should be enforced also cross-language

**Environment (please complete the following information):**
 - @vendure/core version: 1.1.3
 - Nodejs version: 14
 - Database (mysql/postgres etc): postgres

**Comment by martijnvdbrug** [comment]
Hi, thanks for the report.

I've tested it, and it seems to work correct now:
* A single slug can exist once in a single language, but maybe duplicated in other languages. E.g. slug `abc` can exist in English and Dutch. This is expected, because querying the shop-api always uses a single language.
* I also can't reproduce the search issue: Both products are indexed and searchable. Keep in mind that searching also only gives you results for 1 language. 

You can switch languages by appending the graphql endoint with a language code, like so: `shop-api?languageCode=nl`
