### ISSUE TITLE
Add a way to deleted obsolete product options

### ISSUE THREAD

**Issue by filipemoraes** [vendure-ecommerce/vendure#1134]
**Is your feature request related to a problem? Please describe.**
When the product option is no longer used, it is not possible to deleted the option as it remains locked in the option list.

**Describe the solution you'd like**
When there are no variants for the obsolete option, replace the lock icon with an "x" and allow it to be deleted.

**Comment by martijnvdbrug** [comment]
+1 I need this :laughing: I see two options here:

1. The solution as described above: Only allow deletion when there are no variants
2. Always allow deletion and delete the variants that have this option

Side-effect: We might need optionGroup deletion as well, because you could end up with an empty optionGroup after deleting all options.

**Comment by martijnvdbrug** [comment]
Some additional information: The mutation `removeOptionGroupFromProduct` does exist, but it always throws an `PRODUCT_OPTION_IN_USE_ERROR` even after deleting all the variants (verified via GraphQL and checked in the DB if the deleted_at field was filled)
