### ISSUE TITLE
How to deploy vendure for production?

### ISSUE THREAD

**Issue by desfacs-techy** [vendure-ecommerce/vendure#116]
**Describe the bug**
Ho to deploy vendure for production like Heroku?

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - @vendure/core version:
 - Nodejs version : v10.15.3
 - Database (mysql/postgres etc): postgres
**Additional context**

**Comment by desfacs-techy** [comment]
@michaelbromley,

Please assist me, I am unable to deploy it.

**Comment by michaelbromley** [comment]
Hi,

Vendure is a Node app, so if you have any experience deploying a Node app, then it would work in much the same way. A typical method is to run Vendure on a server on e.g. localhost:3000 and then use nginx as a reverse proxy pointing to that. 

Here is a good guide for this kind of setup: https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04

**Note** that since Vendure is still in beta, there are some features missing which would be needed on a real production shop. E.g. payment integrations have not yet been written.

**Comment by desfacs-techy** [comment]
@michaelbromley ,
Thanks for the info.
