### ISSUE TITLE
requestPasswordReset has no argument validation

### ISSUE THREAD

**Issue by Shaokun-X** [vendure-ecommerce/vendure#1240]
**Describe the bug**
The mutation `requestPasswordReset` doesn't do any check, even if I passed in an empty string it still returned `Success`.

I also tested with an email not registered in the Vendure backend, and received the email with a reset link that contains the token.

**To Reproduce**
1. Go to Shop API page
2. Fire a mutation `requestPasswordReset`  with any string you want

**Expected behavior**
Vendure should check if the string is a valid email address, and also see if it belongs to an user in the database.

**Environment (please complete the following information):**
 - @vendure/core version: 1.3.3
 - Database (mysql/postgres etc): sqlite3

**Comment by michaelbromley** [comment]
Hi, thanks for the report.

> I also tested with an email not registered in the Vendure backend, and received the email with a reset link that contains the token.

This should not happen. [This code](https://github.com/vendure-ecommerce/vendure/blob/75130cda2e722cf58cec4f3c32a07e1ff257237b/packages/core/src/service/services/user.service.ts#L205) is supposed to ensure that only email addresses associated with a User will be emailed.

> even if I passed in an empty string it still returned Success.

It is an intentional design decision to _always_ return `{ success: true }`. The reason is that if we return a different response depending on whether that email address is registered, it opens up an attack vector to enumerate all user accounts.

**Comment by Shaokun-X** [comment]
> Hi, thanks for the report.
> 
> > I also tested with an email not registered in the Vendure backend, and received the email with a reset link that contains the token.
> 
> This should not happen. [This code](https://github.com/vendure-ecommerce/vendure/blob/75130cda2e722cf58cec4f3c32a07e1ff257237b/packages/core/src/service/services/user.service.ts#L205) is supposed to ensure that only email addresses associated with a User will be emailed.
> 
> > even if I passed in an empty string it still returned Success.
> 
> It is an intentional design decision to _always_ return `{ success: true }`. The reason is that if we return a different response depending on whether that email address is registered, it opens up an attack vector to enumerate all user accounts.

Thank you for your quick reply! The first thing is my bad, I was mistaken about my emails, sorry!

And I get why it is always success now, thanks for the explanation 💯
