### ISSUE TITLE
ProductVariantId and ProductVariantName don't match when search with groupByProduct 

### ISSUE THREAD

**Issue by datnguyenkieio** [vendure-ecommerce/vendure#1317]
**Describe the bug**
ProductVariantId and ProductVariantName when search with groupByProduct: true is comes from 2 different

**To Reproduce**
Create 2 variants of 1 product then rename first variant to guarantee that if sorted alphabetically it will rank after the 2nd variant

When groupByProduct is true, it will return id of first variant and name of second variant

![image](https://user-images.githubusercontent.com/76099413/147737593-18f1f102-216e-4119-b319-307c52d3f895.png)
![image](https://user-images.githubusercontent.com/76099413/147737630-a97d1c66-c9e3-41da-b924-1fb21b0d4d37.png)

**Expected behavior**
id and name have to be the first variant's

**Environment:**
 - @vendure/core version: 1.2.3 (i tested on 1.4.3 still happen)
 - Nodejs version: v14.17.4
 - Database: postgres 
 - Search plugin: DefaultSearchPlugin

**Comment by michaelbromley** [comment]
This is caused by the way we deal with aggregated columns in the SQL when grouping by product.

In the search index, each row represents a ProductVariant. When we group by product, we add `GROUP BY productId` to the query, but once we do that, we need to apply an aggregate function to each column so the DB knows which value to return.

To solve that we are applying the `MIN()` function: https://github.com/vendure-ecommerce/vendure/blob/81e367244d244db6a525fac21bc9c6dc02f05c7d/packages/core/src/plugin/default-search-plugin/search-strategy/postgres-search-strategy.ts#L270

This is why you get the lowest ID paired with the alphabetically lowest name.

What's the solution? I'm not sure. There might be some better way of handling this, using some different approach to the SQL query which will ensure that the productVariantId and productVariantName columns will always correspond.

**Comment by jakubnavratil** [comment]
This is usually solved with SUBQUERY or maybe this can help, but requires processing the result:
https://www.w3resource.com/mysql/aggregate-functions-and-grouping/aggregate-functions-and-grouping-group_concat.php

**Comment by Izayda** [comment]
The ideal for performance and independent for any rdbms will be logic:
1) Apply filters and get for each product productVariantId
2) Use first block of logic as subquery to fetch product from variants 

Can implement this after 10 January

**Comment by dlhck** [comment]
This issue relates to a version of Vendure that is no longer supported. If the issue persists in the latest version, please open a new issue.
