### ISSUE TITLE
mongodb support

### ISSUE THREAD

**Issue by rrubio** [vendure-ecommerce/vendure#132]
Mongodb compatability as datastore option. SQL solutions require a lot more maintenance and can be more expansive to maintain. Ideally, i'd like to connect the solution to services such as mlab or mongo atlas.

Ideally we'd get and option to provide mongo as a database option.

We've looked at strapi.io (headless cms) which currently supports a number of different databases, however, this is CMS centric and not ideal for ecommerce.

**Comment by michaelbromley** [comment]
Hi,

> SQL solutions require a lot more maintenance and can be more expansive to maintain.

I don't have experience with Mongodb but I'd be interested to know a bit more about how it does better than relational DBs in this regard.

Currently I am doing development with MySQL, Postgres and SQLite and I aim to guarantee compatibility with these 3 database engines. The reason is that:

1. They are very commonly used
2. The nature of the data model is highly relational and to me it makes more sense to store it in a relational rather than document format.

*However*, Vendure uses TypeORM as the data layer, which claims to have some support for Mongodb (see the [config docs here](https://typeorm.io/#/connection-options/mongodb-connection-options)). Thus far, I've not tested Vendure with Mongo and it is highly likely that some or all of it will not work with Mongodb.

I would encourage you to try it out and see. You should be able to connect it up by specifying in your `VendureConfig` object something like:

```ts
const config: VendureConfig = {
  dbConnectionOptions: {
    type: 'mongodb',
    host: 'localhost',
    port: 27017
  }
  // ....
}
```

**Comment by rrubio** [comment]
@michaelbromley thank you for your prompt response! I'll be able to experiment in the next few weeks. I'm proposing your solution to a major retailer as a B2B solution.

Keep you posted.
