### ISSUE TITLE
Change the log level of the 404 and forbidden requests

### ISSUE THREAD

**Issue by ivasilov** [vendure-ecommerce/vendure#1335]
**Is your feature request related to a problem? Please describe.**
The log messages for 404 (whenever a user or google bot tries to access the server directly) are marked as errors.
```
error  [Vendure Server] Cannot GET /daed
error  [Vendure Server] Cannot GET /favicon.ico
```
This also happens whenever a user tries to access the admin, but it redirected to the login page:
```
error.forbidden
Error: error.forbidden
    at AuthResolver.me (.../node_modules/@vendure/core/src/api/resolvers/base/base-auth.resolver.ts:91:19)
    at AuthResolver.me (.../node_modules/@vendure/core/src/api/resolvers/admin/auth.resolver.ts:78:22)
    at .../node_modules/@nestjs/core/helpers/external-context-creator.js:69:33
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
```

**Describe the solution you'd like**
The log level of these two log messages should be warning or info. What can be classified as an error is when someone tries to login and fails because of wrong password.

**Additional context**
Discussed on Slack [here](https://vendure-ecommerce.slack.com/archives/CKYMF0ZTJ/p1640864267062000) and [here](https://vendure-ecommerce.slack.com/archives/CKYMF0ZTJ/p1641400847115000).

**Comment by michaelbromley** [comment]
### What is the appropriate log level for 404 errors?

* https://github.com/symfony/symfony/pull/7993 - Discussion of the same topic for the Symfony framework. Calls to have it either "warning" or "notice" (which I guess corresponds to our "info"?).
* https://stackoverflow.com/a/45424198/772859 Apache demoted 404 from Error to Info.

I am even tempted to demote them even lower to Debug, since they are mostly not relevant to anything and in any case, you would typically have apache/nginx logs which would record all of that if you wanted to e.g. get alerted to an exploit scanning attempt.

Thoughts?

**Comment by skid** [comment]
Practical issues arising from this is that I have to filter out these error messages when setting up error alerts. A 4XX error is an error on the user's side, so it's of little interest to the person running the site. If we want alerts on login or scanning attempts, there are specific metrics that we can set up that depend on the access logs.

I'm for demoting them to info and the failed admin login to warning maybe.
