### ISSUE TITLE
Expose & document FastImporterService

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#1336]
**Is your feature request related to a problem? Please describe.**
Many projects are using custom import scripts. With inventories greater than say 1k SKUs, using the ProductService etc. is not ideal because it is slow. This is due to a lot of validation & error-handling code which is not strictly needed when importing known-good data. Additionally, the core services also fire events which can cause lots of unwanted background work to trigger.

Internally, we have the [FastImporterService](https://github.com/vendure-ecommerce/vendure/blob/f178276cd37ed161597b5f9d354649eb9d315440/packages/core/src/data-import/providers/importer/fast-importer.service.ts#L35), which is what is used when running the `populate()` function exported by `'@vendure/core/cli'`.

This service would be ideal for users building custom import scripts. But currently it is not exported and not documented.

**Describe the solution you'd like**
Export the `DataImportModule` from `'@vendure/core'` and allow the FastImporterService to be easily used externally. Also document the service so it appears in the vendure docs.

**Comment by thardyman** [comment]
There are a lot of useful functions in the `Importer` class that could be exposed.

My use case is we receive a spreadsheet from our supplier containing stock levels and prices of thousands of items that we can resell.  I need to build an importer that will compare each product, by sku, with the one already in our store.  If anything has changed, like price, description or stock level, then I want to update the one in our store.   If a new product appears in the spreadsheet that isn't in our store then I want to import it.

The current `Populate` method is too limited for our case because of these limitations:
- It needs a config file with tax codes and shipping methods, which will cause duplicates every time you run it
- It doesn't check for duplicate products
The `Populate` method has been great to get us started with development though.

I am currently building an importer plugin, and could really use some of the private features that are in the Importer class.  For example the `importProducts` would be massively useful right now.  I've already made use of the `ImportParser` to transform my CSV into an array of products and variants.  I've been able to identify and update existing products. I just want to insert the missing products.

Thanks for all your help and hard work @michaelbromley

**Comment by michaelbromley** [comment]
@amesas So what I am doing for my import (~12k skus) is that I wrote a script which fetches product data from my legacy system and saves it as a CSV file using the vendure [csv import format](https://www.vendure.io/docs/developer-guide/importing-product-data/#product-import-format). 

I then can pass this to the `populate()` function as described [here](https://www.vendure.io/docs/developer-guide/importing-product-data/#populating-the-server). Internally this will then use the FastImporterService. In my case I can import 12k skus in around 5 minutes. So I would expect 150k to take around 1-2 hours.

**Comment by amesas** [comment]
> @amesas So what I am doing for my import (~12k skus) is that I wrote a script which fetches product data from my legacy system and saves it as a CSV file using the vendure [csv import format](https://www.vendure.io/docs/developer-guide/importing-product-data/#product-import-format).
> 
> I then can pass this to the `populate()` function as described [here](https://www.vendure.io/docs/developer-guide/importing-product-data/#populating-the-server). Internally this will then use the FastImporterService. In my case I can import 12k skus in around 5 minutes. So I would expect 150k to take around 1-2 hours.

Thnx for the concise answer :)
