### ISSUE TITLE
Orders can be placed even if some order lines are out of stock

### ISSUE THREAD

**Issue by skid** [vendure-ecommerce/vendure#1355]
This might not be a bug, depending on how you look at it. Woocommerce, for example, does not allow this behaviour:

1. As admin, set the `onHand` value of Product Variant PV1 to 2
2. As a user, add 2 of the PV1 to your order
3. As a user or admin, transition the order to "ArrangingPayment" to simulate that the user has initiated payment
4. As na admin set the `onHand` value of PV1 to 0
5. As a user, transition the order to PaymentSettled

I haven't tested this with 2 users, but I assume the same error will happen if the 2 PV1 items were sold to another user.

Vendure will allow you to place the order and will allocate 2 units of PV1 even though there is not enough on hand. The available quantity will be negative.

This happens because Vendure only checks if there is enough items on stock when the variants are added to the cart. However, variants are only allocated once the order is placed. Situations like this are quite common since user may have a shopping cart with items in it for a long time before deciding to buy it. In the meantime, stock levels may change due to many reasons (sales, returns, damaged, etc..)

Vendure should throw an error each time it tries to allocate more items than available.

**Comment by michaelbromley** [comment]
Let's try to specify what the behaviour _should_ be then.

At step 5, the customer will invoke `addPaymentToOrder`, which when successful, the order will automatically transition to `PaymentAuthorized` or `PaymentSettled`.

Then the sequence is:

1. Check `stockAllocationStrategy.shouldAllocateStock()`
2. If true, call `stockMovementService.createAllocationsForOrder()`

So we are probably talking about throwing an error inside `createAllocationsForOrder()` if there is insufficient saleable stock. However, then we will get into a messy state whereby the payment has been processed, but the order transition has failed.

So actually it would make more sense to prevent the payment from taking place in the first place. Some ideas to explore:

* Check `stockAllocationStrategy.shouldAllocateStock()` **before** the transition takes place and if it returns `true`, have some code that verifies the saleable stock level of each item in the order. If any are insufficient, return `false` to prevent the state transition. This alone will not work because the Payment will have already been processed.
* Check the stock levels before processing a payment, and throw an error if there is insufficient stock. This prevents the order getting into an inconsistent state, _but_ it makes an assumption about stock allocation which might not be true (i.e. if there is a custom `StockAllocationStrategy` defined which allocates stock at some earlier point in the order process).

What are your thoughts on this? How does WooCommerce handle it exactly?

**Comment by skid** [comment]
When I think about it, the solution here is not entirely on the api backend.

In woocommerce, before you click "pay" the quantities in your shopping cart are checked for availability and you get an error if you're trying to pay for an out-of-stock item. Then, the order is transitioned to a "pending payment" state and the purchased quantities are reserved. If a payment is not processed in some amount of time, the reserved quantities are released.

My solution with Vendure is to use a custom `StockDisplayStrategy` and get the exact number of items in stock, perform a check on the frontend and decide whether to allow payment or request the quantities in the active order to be adjusted. A user can, of course, circumvent this by using the GQL api directly, but that's not really an operational issue.

So - maybe there is no api-only solution to this. You are right that once the payment has been made, you have to transition the order, and handle issues like this manually. Automatic solutions require that the payment plugin and frontend play along which is arguable out of Vendure's scope.

The solution would maybe be to add another order state, e.g. "RequiresResolution" where orders that have been paid but can't be fulfilled end up.

**Comment by michaelbromley** [comment]
I'm going to close this for now since a "fix" is not obvious - and as you say there are various userland approaches to handling this per-project.
