### ISSUE TITLE
Admin UI: sort products in the product list

### ISSUE THREAD

**Issue by filipemoraes** [vendure-ecommerce/vendure#1446]
**Is your feature request related to a problem? Please describe.**
As a backoffice user, I would like to order the products.

**Describe the solution you'd like**
Add a dropdown at the top of the product list with the following options:

- Sort creation date in DESC order (default)
- Sort creation date in ASC order
- Sort title in DESC order
- Sort title in ASC order

**Comment by michaelbromley** [comment]
This could be supported very easily if we switched the product list view to be backed by the `products` query rather than the `search` query that we currently use.

Some more context from a discussion on Slack:

> My opinion is that the admin interface search should be implemented as a query against the product/product variant tables. I know it complicates stuff, but you really, ultimately, want a configurable column table of products that can list all possible values, verbatim with advanced filtering.
The search index is just a view on the data and contains information relevant for the user, not the admin.
In our project, we actually built a separate product listing admin page (mostly because we have experience with React and not Angular), and we added custom columns like "applied facets". Here's a screenshot:

<img width="1450" alt="Screenshot 2022-02-25 at 11 55 04" src="https://user-images.githubusercontent.com/6275952/155713758-75e9b81b-0503-4ee8-96f9-a3410f50e932.png">

> How's the speed when listing with the products query?

> It's good enough. We have a f1 micro Cloud SQL instance running Postgres 13. and some 7K products (10k variants) in the database. The TTFB to render this page is around 300ms. The query is not optimized or anything.

**Comment by xrev87** [comment]
On a side note - it would still be useful to support sorting by creation and update dates in search.

**Comment by michaelbromley** [comment]
This was implemented as part of the UI refresh in v2.0!
