### ISSUE TITLE
Postgres Row Level Security

### ISSUE THREAD

**Issue by azfx** [vendure-ecommerce/vendure#1491]
**Is your feature request related to a problem? Please describe.**
How to implement RLS ( Row Level Security ) in Vendure Postgres DB

**Describe the solution you'd like**
Is it possible to implement something like https://github.com/Avallone-io/rls in Vendure ?

**Describe alternatives you've considered**
I have looked in to Vendure Channels, am currently just exploring options. Knowing if RLS is possible or not in Vendure would be nice.

**Comment by ashitikov** [comment]
Hey, yes, this is possible with some modifications. I've implemented RLS in my project as a tenancy solution, but it's not battle-tested yet.

https://github.com/Avallone-io/rls this repo is nice, but since this requires a lot of core modification I've chose another solution:
1. Since vendure uses typeorm, but typeorm does not have ready rls-mechanism, you should implement in by yourself. I used `createQueryRunner()` function https://github.com/typeorm/typeorm/blob/eacecce4a6eedd327dc59e1d3a3114c67ebfdf5b/src/driver/postgres/PostgresDriver.ts#L599 to replace original query runner with yours.
2. Your query runner should override original `connect()` and `release()` functions. You use connect to execute query `await connection.query(`SET "rls.tenantId" = ${tenantId}')` and release to execute `this.databaseConnection.query('RESET "rls.tenantId"')`, where ${tenantId} is your tenant identifier.
3. To pass tenantId to query runner, we either should override every element in the request-response flow or use `AsyncLocalStorage` from `async_hooks` package to write tenantId on the request start, and read it at connect() step in your query runner.
4. Add tenantId to each entity in postgres database. This is kind of boring job, but there is a way to make it a bit faster. You should operate with typeorm metadata storage in this way: 
```
storage.columns.push({
        target: t.target,
        propertyName: 'tenantId',
        mode: 'regular',
        options: {
          nullable: true,
          select: false,
          update: false,
          default: () => "NULLIF(current_setting('rls.tenantId', true), '')::UUID"
        }
      })
```
This will add new column at runtime to the target. Use for-in loop to iterate typeorm's tables.
5. Vendure adds some uniqueness constraints and unique indices in some tables. This means you should override such indices and unique constraints to honor tenantId, or you will not be able to have some entities with the same code even they are not the same tenant. Use for-in loop to iterate typeorm's indices and unique constraints.
6. Create migration to enable row-level security on each table like this:
```
await queryRunner.query(`ALTER TABLE "vendure"."channel" ENABLE ROW LEVEL SECURITY`)
await queryRunner.query(`CREATE POLICY tenant_isolation_policy ON "vendure"."channel" USING ("channel"."tenantId" IS NOT DISTINCT FROM (NULLIF(current_setting('rls.tenantId', true), '')::UUID))`)
```
7. Do not forget to create additional role for postgres, because owner bypasses RLS anyway.
8. Patch vendure's `ChannelService` and `ZoneService`. https://github.com/vendure-ecommerce/vendure/blob/4d55949b052f900e2221b681a40908bd8a3a77d5/packages/core/src/service/services/channel.service.ts#L72 Vendure maintains refreshable caches at some services, so you have to override default cache to make it tenant-dependent. Function `ChannelService/ZoneService.createCache()` is a factory-function, just put your cache instead of default one.
9. Implement your own tenant-dependent cache solution (this is quite-easy). Use `AsyncLocalStorage` in the same way as you did in your own postgres query runner.
10. Implement middleware and apollo-server plugin to introduce tenancy. You write tenantId in `AsyncLocalStorage` at the request start. You can read it either from header or from subdomain. Note that there is some issues, that apollo-server may loose async_hooks promise context, so that is why apollo-server plugin is also required as middleware. At middleware level you use `asyncLocalStorage.run({ tenantId }, next)`, at apollo-server plugin use `asyncLocalStorage.enterWith({ tenantId })`.

**Comment by azfx** [comment]
hey @ashitikov , thanks for your response with such details, appreciate it. I will try as well, and share my feedback.

**Comment by dr996x** [comment]
hey @ashitikov, I'm really interested in this, would you be willing to share the code for the modifications you've made?

**Comment by xrev87** [comment]
hey @ashitikov, I'm really interested in this, would you be willing to share the code for the modifications you've made?

**Comment by ashitikov** [comment]
Hey yes, I do. This will require some time for me to wrap it to plugin

**Comment by cyraid** [comment]
@ashitikov Hi Ash, any progress?

**Comment by michaelbromley** [comment]
Closing this as it is not currently on our roadmap to support. Thanks all for sharing solutions & feedback.
