### ISSUE TITLE
Admin customers list is broken while upgrade to 1.6

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/vendure#1569]
**Describe the bug**
 Admin customers list is broken while upgrade to 1.6, 
 ```
{
  customers(options:{
    filter: {
     emailAddress: {
      contains:""
    },
      lastName : {
        contains:""
      },
// remove postalCode is works fine.
      postalCode:{
        contains : ""
      }
    }
  }) {
    items {
      id
    }
  }
}
```

**To Reproduce**
1. /customer/customers
2. throw error 
![image](https://user-images.githubusercontent.com/2833251/169192035-a070e59a-f255-4053-82b4-88582ccaf9a7.png)
3. See error

**Expected behavior**

**Environment (please complete the following information):**
 - @vendure/core version: 1.6
 - Nodejs version V17
 - Database (mysql/postgres etc): mysql

**Additional context**

**Comment by michaelbromley** [comment]
We debugged this together and traced it down to this function: https://github.com/vendure-ecommerce/vendure/blob/37a9402c54be6bb1dff8a591cb3ed2ef0f75c809/packages/core/src/service/helpers/list-query-builder/list-query-builder.ts#L305-L322

The `entityMetadata` was not finding his `address` table and the reason is that he has defined a global entity prefix "glass" in his dbConnectionOptions. So the `em.tableName === tableNameLower` part was comparing `'address'` to `'glass_address'` and coming up undefined.
