### ISSUE TITLE
queries on `collection.assets` fail (and also `collectionService.findAll()` does not returns assets

### ISSUE THREAD

**Issue by lsimone** [vendure-ecommerce/vendure#157]
**Description**
I tried both: through graphql and through `collectionService.findAll()`.
In both cases there are problems to get `collection.assets` array.

The service returns an object without `assets` (`featuredAsset` is present, instead)

**To Reproduce**
This query to the vendure demo fails:
`curl 'https://demo.vendure.io/shop-api' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: https://demo.vendure.io' --data-binary '{"query":"{\n collections {\n items {\n assets {\n name\n }\n }\n }\n}"}' --compressed
`

**Expected behavior**
Assets should be returned from both graphql response and collection service.

**Comment by michaelbromley** [comment]
Note that although this is closed by the referenced commit, this only applies to the GraphQL API.

When dealing directly with the `CollectionService`, you'll want to make a call to `AssetService.getEntityAssets(collection)` to get the array of assets.

**Comment by lsimone** [comment]
mmmh @michaelbromley but it's not like this for `featuredAsset`, for instance:
```
const res = collectionService.findAll(ctx)
const feat = res.items[0].featuredAssets     // this is not null
const assets = res.items[0].assets              // this IS null
```
Is that needed/wanted?

**Comment by michaelbromley** [comment]
That's true. The reason is that the `CollectionService.findAll` method already joins the `featuredAsset` relation:
https://github.com/vendure-ecommerce/vendure/blob/e2e43ea4df2bb3cf3c77ea854d5f66785fe3fcc2/packages/core/src/service/services/collection.service.ts#L92

The basic issue here is that up until now, the internal Service layer has not been targeted at external use. Therefore there are parts which are inconsistent or surprising for an outside developer.

On one hand, it would be *consistent* not to join *any* relations implicitly. This means that consumers of the service know for sure that they'll have to join any relations they need themselves.

This however would imply significant performance impact since common SQL joins would then be replaced by individual DB calls. So up until now I've tried to strike a balance and join those relations which I think will commonly be needed, and omit the others. This is why such inconsistencies as `featuredAsset` vs `assets` exists.

**Comment by lsimone** [comment]
makes sense. 
Thank you @michaelbromley .
