### ISSUE TITLE
Collections hierarchy has no effect on sub-collections

### ISSUE THREAD

**Issue by lsimone** [vendure-ecommerce/vendure#158]
**Describe the bug**
The nested collection filters products without taking into account the parent collection filtering.

**To Reproduce**
Just create a collection child inside a parent collection, bind them to different facets: the child could have products that are not in the parent collection.

**Expected behavior**
If I have a collection child `C` and a collection parent `P`, I expect that `C` filters products according to its own rules, but on a product pool that is the P's one, not the entire products database.

**Comment by michaelbromley** [comment]
Although there are e2e tests in place which should detect this, after much investigation there seems to be an edge case where a single matching FacetValue on a ProductVariant gets matched multiple times if the Product has more than one FacetValue.

I'm adding a test for this case so that it can be fixed and not regress in future.

**Comment by michaelbromley** [comment]
Wow that was a tough one to fix! But great catch - it turns out the logic for facetValue-based collections was quite badly wrong and just *happened* to work in the range of scenarios in the e2e tests.

**Comment by lsimone** [comment]
GJ! 
It has been great to fix it before the stable ;-)
