### ISSUE TITLE
Cannot recreate administrator with same email address

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#1590]
I create an administrator with an email and delete it. Later when I create a new administrator with the same email, the error of a duplicate key is thrown. Lets solve it please.

**Comment by michaelbromley** [comment]
Just realized this is a duplicate of #1523. Since v1.6 you can use [metadataModifiers](https://www.vendure.io/docs/typescript-api/configuration/entity-options/#metadatamodifiers) to alter the DB schema in a safe way.

See [the example in this comment](https://github.com/vendure-ecommerce/vendure/issues/1523#issuecomment-1144531739)
