### ISSUE TITLE
Not able to perform file upload e2e vendure testing

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#1671]
I run a file upload mutation on vendure and it always crashes with fatal javascript size issue.

I tried with node version 18.0.0 and v16.3.1 and both had same issue whenever I call "fileUploadMutation" of vendure testing admin or shop client and add files name to filePaths, I get this issue. I have attached the code snippet and 

`const filesToUpload = [
            path.join(__dirname, 'fixtures/assets/dummy.txt'),
        ];`

        `const createdIt = await adminClient.fileUploadMutation({
            mutation:CREATE_MERCHANT,
            filePaths: filesToUpload,
            mapVariables: filePaths => ({
                input: {
                    adminFirstName: "Biplab",
                    adminLastName: "Karki",
                    adminEmail: "biplab@d.co",
                    adminPassword: "abcd",
                    adminPhoneNumber: "1122334",
                    companyCode:"MENZZ",
                    companyName: "Menzz Co. Ltd.",
                    companyAddress: "Kirtipur-2, Kathmandu",
                    companyDescription: "All about men's grooming",
                    customerContactEmail:"info@menzz.co",
                    customerContactPhone:"00000",
                    enabled: true,
                    document: filePaths.map(() => ({ file:null })),
                }
            }),
        })`

The following is my input schema for this:

```
`input CreateMerchantInput {
    adminFirstName: String!
    adminLastName: String!
    adminEmail: String!
    adminPassword: String!
    adminPhoneNumber: String
    companyCode: String!
    companyName: String!
    companyAddress: String
    companyDescription: String
    customerContactEmail: String
    customerContactPhone: String
    enabled: Boolean
    document: Upload
}

createMerchant(input: CreateMerchantInput!): Merchant!

`
```
<img width="1440" alt="Screen Shot 2022-07-21 at 17 19 16" src="https://user-images.githubusercontent.com/29729738/180212349-1fc4587e-c6a8-4dd3-800f-e23ac583320c.png">

**Comment by michaelbromley** [comment]
Hi, thanks for the report. Would you be able to create an actual git repo which I could simply clone and run in order to see the issue? It will make it much more likely that I find the time to look into this sooner.

**Comment by BeepLoveKarki** [comment]
Sure here it is.

https://github.com/BeepLoveKarki/merchant-repo

**Comment by toBeOfUse** [comment]
I also encountered this issue. After googling, I found advice to delete node_modules and reinstall it, and for some reason, that worked. Definitely a weird problem.

**Comment by toBeOfUse** [comment]
Actually, it does seem to be recurring. The weird thing is that the resolver for my mutation completes just fine; I can tell from logging that it runs all the way up to the return statement. The problem seems to happen after the resolver returns the created object.

**Comment by toBeOfUse** [comment]
Actually, disregard the above; I was mistaken about deleting node_modules fixing the problem, and misled by vitest's interception of console.log statements (they were getting intercepted and then never output due to Node.js crashing.) The actual problem for me is an infinite loop in `objectPath`:

https://github.com/vendure-ecommerce/vendure/blob/7bba9073890b1f2c5131e5585a0283932c011db7/packages/testing/src/utils/create-upload-post-data.ts#L54-L73

In my example, which is very similar to the original one, it's being called with this object as `variables`, and i = 0:

```js
{
  input: {
    name: "Bob's Shop",
    logo: null,  // this is meant to be the Upload input
    sellerExternalObject: { externalId: "bob-shop-123", externalSource: "test-source" },
  },
}
```

I am sort of unclear on how `objectPath` is meant to work. It should be finding the paths to the `null` values, right? But it always assumes that the first property of the object it's passed is going to lead to the `null` value that it's finding the path to. This causes a problem where it recurses endlessly into the `name` field given the input above: it reaches name, and then pulls out the first character of `name` ("B"), and then pulls out the first character from that one-character string (also "B"), and then repeats that infinitely, adding an endless stream of `0`s to the path as it gets the 0th character over and over until Node.js crashes.
