### ISSUE TITLE
tsvector COLUMN and GIN index are dropped by synchronize

### ISSUE THREAD

**Issue by roytan883** [vendure-ecommerce/vendure#1695]
**Describe the bug**
dbConnectionOptions.synchronize = true,  will drop table customed COLUMN and GIN index.

**To Reproduce**
1.
```
alter TABLE shop_vendure.search_index_item add COLUMN rts_tsv_sku tsvector;
alter TABLE shop_vendure.search_index_item add COLUMN rts_tsv_pn tsvector;
alter TABLE shop_vendure.search_index_item add COLUMN rts_tsv_pvn tsvector;
CREATE INDEX search_index_item_rts_tsv_sku_idxg ON shop_vendure.search_index_item USING GIN (rts_tsv_sku);
CREATE INDEX search_index_item_rts_tsv_pn_idxg ON shop_vendure.search_index_item USING GIN (rts_tsv_pn);
CREATE INDEX search_index_item_rts_tsv_pvn_idxg ON shop_vendure.search_index_item USING GIN (rts_tsv_pvn);
```
2.
restart server
3.
those COLUMN and index are dropped

**Expected behavior**
If custom COLUMN  and index not conflict with `typeorm`, should not be dropped

**Environment (please complete the following information):**
 - @vendure/core version: 1.6.4
 - Nodejs version: 12
 - Database: postgres 14

**Comment by michaelbromley** [comment]
Hi,

This is by design really. TypeORM is in change of the DB schema, and will only respect column data that is registered via TypeORM decorators or metadata.

In this case, you are adding columns to the SearchIndexItem entity, so you should be able to do this in a way which will survive TypeORM migrations by defining them via an [EntityMetadataModifier](https://www.vendure.io/docs/typescript-api/configuration/entity-options/#entitymetadatamodifier) which you pass to your VendureConfig `entityOptions.metadataModifiers` array. It's a bit of an advanced technique, and will probably require some trial-and-error to get right.
