### ISSUE TITLE
query `search` throw error while `term` contains character `-` for mysql

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/vendure#1808]
**Describe the bug**
mutation `search` throw error while `term` contains character `-` for mysql

**To Reproduce**
1. https://localhost:3001/shop-api  (BTW vendure offical demo is works fine (`not mysql driver?`) ) 
2. query 
```gql
{
  search(input:{
    groupByProduct:false,
    take: 2,
    term:"sdf-",
    sort: {
      price:DESC
    }
  }) {
  	items {
      productId
      slug
    }
  }
}
```
4. the search result will give error
```json
{"data":null,"errors":[{"message":"syntax error, unexpected $end, expecting FTS_TERM or FTS_NUMB or '*'"}]}
```

**Expected behavior**
```json
  {
    "data": {
      "search": {
        "items": []
      }
    }
  }
```
**Environment (please complete the following information):**
 - @vendure/core version: 1.7.3
 - Nodejs version 16
 - Database (mysql/postgres etc): mysql

**Additional context**

**Comment by michaelbromley** [comment]
It looks like this is because `-` is a boolean mode operator in this Mysql full text search: https://dev.mysql.com/doc/refman/8.0/en/fulltext-boolean.html

There are also other characters that cause an error - so far I discovered:

- `@`
- `+` (trailing)
- `*` (trailing)
- `~` (trailing)
- `<` (trailing)
- `>` (trailing)

**Comment by tianyingchun** [comment]
should escape these search query character in vendure?
