### ISSUE TITLE
Standalone Admin UI and custom fields

### ISSUE THREAD

**Issue by cermakondrej** [vendure-ecommerce/vendure#1818]
**Describe the bug**
When compiling Admin UI as standalone app as per docs, there is no way to pass the vendure config, therefore custom fields are not getting rendered in admin UI.

**To Reproduce**
To reproduce this issue, simply create vendure admin ui app same as in docs and it will not contain custom fields in vendure config.

**Expected behavior**
A way to pass either whole vendure config or at least custom fields to reconize them during compiling.

**Environment (please complete the following information):**
All vendure versions

**Comment by michaelbromley** [comment]
Hi,

The Admin UI does not require the VendureConfig to know what custom fields are defined. Instead, it makes an API call to the server, which supplies all the data on the configured custom fields, which the Admin UI then uses to display the appropriate form inputs.

So I'm not sure what the issue is that you are running into here. You can check in your network tab and see if, after logging in, the Admin UI makes an API call with the `GetServerConfig` query, which should return an object with 

```
globalSettings -> serverConfig -> customFieldConfig
```

which should contain the custom field config data.
