### ISSUE TITLE
TaxRateService Cache Performance Issue

### ISSUE THREAD

**Issue by Zizitto** [vendure-ecommerce/vendure#1856]
**Describe the bug**
There is a performance issue with TaxRateService.getApplicableTaxRate method.

TaxRateService.getApplicableTaxRate method is frequently used in the price calculation strategy, price-related field resolvers, and a lot of other places.
This method is invoked multiple times per single request because each field resolver processing is an async process.
Each time this method tries to get all tax rates from cache. 
This cache is almost always empty because the previous call to this method is not finished yet.
Also, the cached value is not available in 99% of cases because previously it was written using RequestContextCacheService which shares cached value only with a single RequestContext (during a single request).

That Issue causes a lot of requests to DB.
As for me tax rates cache value should be written once on OnApplicationBootstrap, and should be available for use on the server level (not each request)

**To Reproduce**
- Enable DB query logging.
- Try to Invoke any endpoint which returns multiple product variants. 
- Try to get "price" and "priceWithTax" properties from product variants.
- Look at DB logs, there are multiple query calls like:
`SELECT "TaxRate"."createdAt" AS "TaxRate_createdAt", "TaxRate"."updatedAt" AS "TaxRate_updatedAt", "TaxRate"."name" AS "TaxRate_name", "TaxRate"."enabled" AS "TaxRate_enabled", "TaxRate"."value" AS "TaxRate_value", "TaxRate"."id" AS "TaxRate_id", "TaxRate"."categoryId" AS "TaxRate_categoryId", "TaxRate"."zoneId" AS "TaxRate_zoneId", "TaxRate"."customerGroupId" AS "TaxRate_customerGroupId", "TaxRate__category"."createdAt" AS "TaxRate__category_createdAt", "TaxRate__category"."updatedAt" AS "TaxRate__category_updatedAt", "TaxRate__category"."name" AS "TaxRate__category_name", "TaxRate__category"."isDefault" AS "TaxRate__category_isDefault", "TaxRate__category"."id" AS "TaxRate__category_id", "TaxRate__zone"."createdAt" AS "TaxRate__zone_createdAt", "TaxRate__zone"."updatedAt" AS "TaxRate__zone_updatedAt", "TaxRate__zone"."name" AS "TaxRate__zone_name", "TaxRate__zone"."id" AS "TaxRate__zone_id", "TaxRate__customerGroup"."createdAt" AS "TaxRate__customerGroup_createdAt", "TaxRate__customerGroup"."updatedAt" AS "TaxRate__customerGroup_updatedAt", "TaxRate__customerGroup"."name" AS "TaxRate__customerGroup_name", "TaxRate__customerGroup"."id" AS "TaxRate__customerGroup_id" FROM "tax_rate" "TaxRate" LEFT JOIN "tax_category" "TaxRate__category" ON "TaxRate__category"."id"="TaxRate"."categoryId"  LEFT JOIN "zone" "TaxRate__zone" ON "TaxRate__zone"."id"="TaxRate"."zoneId"  LEFT JOIN "customer_group" "TaxRate__customerGroup" ON "TaxRate__customerGroup"."id"="TaxRate"."customerGroupId" WHERE "TaxRate"."enabled" = $1 -- PARAMETERS: [true]"}`

**Expected behavior**
DB call should be invoked once, or not invoked at all.

**Environment (please complete the following information):**
 - @vendure/core version: any
 - Nodejs version: any
 - Database (mysql/postgres etc): any

**Comment by michaelbromley** [comment]
Hi,
Thanks for the report! I've just looked into this and it does indeed seem that the query to fetch the tax rates is executed more than expected. The way the RequestContextCache is _supposed_ to work is that the first invocation will cache the _Promise_ returned by the DB call, and subsequent invocations will use this exact same promise to resolve the value. So in theory the DB call should only be made at most once per request. 

So something is going wrong with that mechanism, which I need to dig in to.

> As for me tax rates cache value should be written once on OnApplicationBootstrap, and should be available for use on the server level (not each request)

This is actually how it worked originally, but that was changed in this commit: 5b719248. The reason is that caching things on bootstrap (and then only updating that cache when e.g. a TaxRate is changed) only works in a single-instance deployment. If we have multiple Vendure servers in parallel, e.g. in a horizontally-scaled deployment, this cache can get out of sync between instances. If we update a TaxRate, only the cache of _that one instance_ will get updated. The others will all be stale.

Another potential approach is to use a cache with a TTL (expiry time) like we do with [ChannelService](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/service/services/channel.service.ts#L46) where the cache will get refreshed only if it is more than e.g. 30s old. This is a compromise that can still lead to stale values in a multi-instance deploy, but it limits the staleness to a very short time period.

**Comment by Zizitto** [comment]
I like the solution you just committed, that is much better than request context cache. Thanks.

**Comment by michaelbromley** [comment]
Closing this as we now use a TTL-based cache for the tax rates.
