### ISSUE TITLE
Vendure got capped at 30 request / second regardless the hardware specification

### ISSUE THREAD

**Issue by ThaiLB-TheGreat** [vendure-ecommerce/vendure#1895]
**Describe the bug**
I am running a load test by using Jmeter. I noticed that when I raised concurrent request to more than 30 requests, Vendure failed at responding. For example, I ran the test with 50 concurrent users, 30 requests passed and 20 requests failed.

**To Reproduce**
1. Using Jmeter (Latest version).
2. Build request to create an order (Adding item status)
3. Run with with 50 threads.

**Expected behavior**
My instance was having 8 CPU core, 16G of memory and hosted on Azure, running Ubuntu 20.04. I expected Vendure can handle at least 1000 concurrent users at moment.

**Environment (please complete the following information):**
 - @vendure/core version: 1.4.0-beta.0 (2021-12-06)
 - Nodejs version: v16.15.1
 - Database (mysql/postgres etc): Postgresql 14

**Additional context**

**Comment by michaelbromley** [comment]
Hi @ThaiLB-TheGreat thanks for the report!

First thing to realize is that Node.js is single-threaded, **so perf is bounded by the speed of a single core**. You can have a 32 core server but Vendure will only be using 1 of those cores! (ok, 2 if we are including the worker process)

16GB ram is also more than enough for most instances.

So we have 2 avenues to improve perf:

1. Improve the speed of Vendure itself.
2. Utilize more cores

I notice that you are on v1.4.x. This is quite an old version and a lot of perf work was done since then, especially on v1.6. You can read [this issue to see details of the benchmarks](https://github.com/vendure-ecommerce/vendure/issues/1506) and improvements we applied.. So first of all I'd be interested to see if upgrading to the latest version has any effect on your results.

> Build request to create an order (Adding item status)

Also the specific request you perform will affect the throughput. Mutations that manipulate an order are some of the most computationally expensive (and thus slowest), because there is a lot of logic that needs to run in terms of checking and applying promotions, pricing strategy, and so on.

Also the shape of the GraphQL query will have an impact - queries which select lots of nested data can trigger field resolvers and also then demands work from the graphql library to walk the resulting object tree.

To use multiple cores, you can use the pattern of having a load-balancer that distributes incoming requests to each of the running servers. For example, you could [use pm2 to do this](https://pm2.io/blog/2018/04/20/Node-js-clustering-made-easy-with-PM2). In this case you should also read [these docs on multi-instance deployments](https://www.vendure.io/docs/developer-guide/deployment/#serverless--multi-instance-deployments).

**Comment by michaelbromley** [comment]
Closing this as there's no specific actionable work to be done. As mentioned above, we did a lot of performance work since then too.
