### ISSUE TITLE
Consider switching TypeORM to MicroORM

### ISSUE THREAD

**Issue by mindreframer** [vendure-ecommerce/vendure#1925]
First of all: thanks for this project! I'm looking into shopping systems now, and Vendure is standing out in terms of flexibility and meaningful features. I love your approach to testing, it looks super-maintainable! 

**Is your feature request related to a problem? Please describe.**
The amount of issues with label "bug" for TypeORM does not look sustainable - https://github.com/typeorm/typeorm/issues?q=is%3Aissue+is%3Aopen+bug - ca. 1050 issues. By relying on it, Vendure and its users/developers inherit all those problems. 

**Describe the solution you'd like**
MicroORM looks very similar, yet seems in much better shape considering the number of issues: https://github.com/mikro-orm/mikro-orm/issues?q=is%3Aissue+is%3Aopen+label%3Abug (7 open as of today) 

**Additional context**
This is a rather invasive and big change (also considering existing apps / plugins), yet it would simplify the longterm development. Maybe it's better to do it now, before vendure becomes super-popular ;) Since 2.0 is imminent, targeting 3.0 for next year with a clear path for upgrading plugins / etc would be a great step towards having a stable foundation. 

Cheers, 
Roman

**Comment by michaelbromley** [comment]
Hi Roman,

Thanks for the suggestion. Have you used Mikro ORM in a large project? In my experience, it's difficult to really appreciate the true nature of a complex library like this without building something significant with it which gives you ample opportunity to rub up against all the rough edges. 

It's true that TypeORM has a bunch of rough edges, and looking at the issue activity of Mikro ORM, the maintainer seems to be very active which is great.

### Usage vs issues

One thing worth noting is that TypeORM has an order of magnitude more usage than Micro ORM:
![image](https://user-images.githubusercontent.com/6275952/206451665-e483f95b-721c-4b0d-b514-cfbf1745ff7d.png)
![image](https://user-images.githubusercontent.com/6275952/206451709-eb9c754b-ea5c-44fe-a9b8-9c6d1721e2fd.png)

Total npm downloads over past 2 years:

- mikro-orm: **2,818.360**
- typeorm: **85,427,471**

This needs to be taken into consideration when looking at the number of issues in a repo. If Mikro ORM had similar usage, I wonder how the maintainer would manage the influx of issues & support requests that inevitably flood in, many of them spurious yet still requiring maintainer time to investigate and triage. As a point of reference, React and Angular both currently have around 1k open issues, and these are projects maintained by dedicated full-time teams. Perhaps an even better comparison is **Prisma** - which has a slightly fewer downloads than TypeORM, and is backed by a large company of full-time devs, yet has over 2.3k open issues.

---

All of which is to say: I am aware of the rough edges of TypeORM and I can certainly imagine that another library could do things better, but it's really hard to know whether MikroORM _is_ unequivocally that library, without having some serious real-world, long-term experience with it at a comparable scale to TypeORM.

As you correctly point out, migrating the ORM layer is a massive change, affecting all parts of Vendure and its ecosystem. Even the migration from TypeORM 0.2.x to 0.3.x which is coming as part of v2 is a significant undertaking, and that's with probably 80% of the APIs being unchanged.

For me, to justify moving away from TypeORM there needs to be real, compelling reasons or for me to totally lose confidence in the future of TypeORM. Right now neither of those are the case - if anything TypeORM maintenance has improved quite a bit over the past year or so.

So I'm going to close this issue: TypeORM is "good enough" and the rough edges mostly do not cause many issues. I'd rather invest development effort into making PRs to fix TypeORM issues (which I've done quite a few of in the past), rather than go for a big migration.

But thanks again for taking the time to suggest ways to potentially improve Vendure! It is just this kind of thinking that makes an OSS project better when we all get together and share & learn from one another.

**Comment by mindreframer** [comment]
Hi Michael! 

Thanks for the comprehensive answer! I fully understand the reasons you outlined and as you have said, "good enough" is better than perfect and your experience with TypeORM required lots of time, that would be lost when switching ORMs. 

Thanks you for taking it professionally, this attitude shines throughout your work and makes every interaction a great experience. I'm going to give Vendure a try! 💙
