### ISSUE TITLE
Adding plugins to vendure-config, giving error "Nest can't resolve dependencies of the ConfigModule"

### ISSUE THREAD

**Issue by mr-vara** [vendure-ecommerce/vendure#1977]
**Describe the bug**
If I add plugins to vendure-config, If I add any plugins, it's giving error. I tried to add ElasticSearch Plugin as mentioned [here](https://www.vendure.io/docs/typescript-api/elasticsearch-plugin/) in the official documentation.

I'm getting the following error when I run the project:
```
Nest can't resolve dependencies of the ConfigModule (ConfigService, ?). Please make sure that the argument ModuleRef at index [1] is available in the ConfigModule context.

Potential solutions:
- If ModuleRef is a provider, is it part of the current ConfigModule?
- If ModuleRef is exported from a separate @Module, is that module imported within ConfigModule?
  @Module({
    imports: [ /* the Module containing ModuleRef */ ]
  })

Error: Nest can't resolve dependencies of the ConfigModule (ConfigService, ?). Please make sure that the argument ModuleRef at index [1] is available in the ConfigModule context.
```
I tried to add ElasticsearchPlugin to imports: [ElasticsearchPlugin] in ConfigModule. But still, I'm getting the same issue.

This is what I tried to resolve:

1. I followed [this](https://www.vendure.io/docs/typescript-api/elasticsearch-plugin/) to integrate the plugin.
2. Then, after getting the issue, I tried to add imports: [ElasticsearchPlugin] in ConfigModule and AppModule.
3. Then, the error is still the same, So, I tried to add the ElasticsearchPlugin to the imports, exports, and providers array. Still the same issue.

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.0-next.22
 - Nodejs version: v18.12.1
 - Database (mysql/postgres etc): mysql

Could anyone please help me with this?
Thanks in Advance.

**Comment by tschortsch** [comment]
I'm currently getting the same error when I try to use a custom plugin. Strangely the issue only appears when the npm dependencies are installed in the plugin (`node_modules` folder exists). As soon as I remove it the plugin works as expected.

**Comment by michaelbromley** [comment]
Hi @tschortsch, what dependencies does your custom plugin have?

**Comment by michaelbromley** [comment]
The reason is that, since your plugin is part of an existing Vendure project (which already has all the dependencies), your plugin does not need its own dependencies.

Your plugin only needs its own package.json and dependencies if you are developing it in isolation from a vendure project, e.g. if you are building a stand-alone plugin for distribution via npm.

**Comment by tschortsch** [comment]
So as soon as there is a `node_modules/@vendure` folder inside `src` or `src/plugins` or deeper the startup of my vendure instance fails 🤔 even if I'm not importing my plugin in the vendure config. So I guess it's not really related to the plugin itself.

**Comment by michaelbromley** [comment]
This is related to the way imports are resolved in node. The closest node_modules in the directory tree is checked first, and then upwards until the root directory is reached. You should usually avoid having more than one node_modules dir unless you are working with a monorepo type setup.

**Comment by HoseinGhanbari** [comment]
This issue is really annoying, actually for those who want start building new plugins. You just clone the [Vendure plugin template](https://github.com/vendure-ecommerce/plugin-template#vendure-plugin-template) and go through the initialization steps BUT it wont work 💥We should at least warn the new developers and let them getting started without any errors.

Related question on stackoverflow
https://stackoverflow.com/questions/75054103/

**Comment by HoseinGhanbari** [comment]
Also worth noting that [Vendure plugin template](https://github.com/vendure-ecommerce/plugin-template#vendure-plugin-template) is not compatible with newer version of `"@vendure/*` dependencies. For example the `compatibility` property has not defined for `@VendurePlugin` as it's now a requirements due to newer `VendurePluginMetadata`.

**Comment by TheValkDokk** [comment]
A year late, but if anyone still have this problem when using a Custom plugin that have multiple services and if those services  depends on each other, use [Forward reference](https://docs.nestjs.com/fundamentals/circular-dependency)

**Comment by michaelbromley** [comment]
I'm closing this as I don't see a specific issue with Vendure itself - rather a combination of various configurations interacting badly to cause errors.
