### ISSUE TITLE
having email template files in own plugin directory

### ISSUE THREAD

**Issue by Logic-Bits** [vendure-ecommerce/vendure#2008]
Hello,

when writing a plugin (with own emails) i have to put the tempaltes files in the email plugin directory.
I can only customize the name, but not the directory for a single EmailEventHandler.
That makes it hard to "only" install the plugin only by adding a single Plugin(folder).

Please correct me if im wrong :)

Thanks!

**Comment by dlhck** [comment]
This looks like a general support request rather than an issue specifically related to this project. For community support, you are welcome to join our [Discord community](https://vendure.io/community) where you can post your question in the `#help` channel. In case your company needs dedicated support please reach out to us [via our contact form](https://vendure.io/contact).

If you think I've made a mistake and this is indeed an issue specific to this project, please reply and the issue can be re-opened if needed.
