### ISSUE TITLE
Update to Nest.js v9 for Vendure v2

### ISSUE THREAD

**Issue by mattgills** [vendure-ecommerce/vendure#2068]
**Is your feature request related to a problem? Please describe.**
There is a vulnerability in `@nestjs/core` before `9.0.5`, per [CVE-2023-26108](https://www.cve.org/CVERecord?id=CVE-2023-26108).  Since the latest Vendure v2 branch is using `@nestjs/core` v8, it may make sense to continue the upgrade to v9.

**Describe the solution you'd like**
If possible, bump dependencies to the latest versions, so that resolving vulnerabilities is simpler.

**Describe alternatives you've considered**
Currently I do not see resolutions to this vulnerability that are in v8, but we could ask `@nestjs/core` if they will patch v8.  Nonetheless, it still seems better to just go to the latest.

**Additional context**
None

**Comment by michaelbromley** [comment]
Hi Matt,

This is already done in the major branch: https://github.com/vendure-ecommerce/vendure/commit/d3595ba9d0bfcc3c70539c6dd7a466aba207b5f5

**Comment by mattgills** [comment]
Ah ok I was looking in the wrong place - thanks, Michael! 😄

**Comment by denz93** [comment]
@michaelbromley Do you consider re-export NestJS core/common in Vendure-Core so that plugin developers can import NestJS modules from there? 

Reason: During developing plugins, we often use some modules in Vendure and some in NestJS(graphql, cache, etc). And it could lead to mismatch NestJS version between what Vendure uses and developers install.
