### ISSUE TITLE
Stripe Payment Plugin:  How can we add session expiry and line Items 

### ISSUE THREAD

**Issue by tufail** [vendure-ecommerce/vendure#2074]
Hi , 
I am looking for the feature where I can post my complete order "list_items" to stripe. Here I can see we are saving total and orderCode to stripe but not the whole items. Also I like to know how can I set sessions expiry to stripe for recover abandoned carts. Here is the document (https://stripe.com/docs/api/checkout/sessions/create?event_types-payment_intent.payment_failed#create_checkout_session-line_items) from stripe to save session data and expiry but I am not clear how can I post this to @vendure/payment (stripe).
 
What I am trying here is
```
const session = await stripe.checkout.sessions.create({
    payment_method_types: ["card"],
    success_url: `url`,
    // if payment fails
    cancel_url: `fallbackUrl`,
    customer_email: activeOrder.customer.emailAddress, 
    //  all line items data
     line_items: [ {
         id: 123,
         price: 5000,
         quantity: 1,
      }],
     expires_at : 1678783453,
     consent_collection: {
      promotions: 'auto'
    },
   //....   
  });
```

**Comment by dlhck** [comment]
This looks like a general support request rather than an issue specifically related to this project. For community support, you are welcome to join our [Discord community](https://vendure.io/community) where you can post your question in the `#help` channel. In case your company needs dedicated support please reach out to us [via our contact form](https://vendure.io/contact).

If you think I've made a mistake and this is indeed an issue specific to this project, please reply and the issue can be re-opened if needed.
