### ISSUE TITLE
Docker - backend

### ISSUE THREAD

**Issue by rrubio** [vendure-ecommerce/vendure#208]
**Is your feature request related to a problem? Please describe.**
Have you been able to Dockerise the backend?

**Describe the solution you'd like**
It would be great to run the entire backend project on Docker by default.

**Describe alternatives you've considered**
The alternative will be to host on a dedicated server.

**Additional context**
-

**Comment by michaelbromley** [comment]
Yes, take a look at the demo project repo: https://github.com/vendure-ecommerce/vendure-demo

This uses Docker and the pm2 process manager to power https://demo.vendure.io

Since it's just a demo, it uses SQLite as the database. Adding something like postgres would be a matter of using Docker Compose to add a postgres image I guess.

**Comment by rrubio** [comment]
Awesome! thank you man.
