### ISSUE TITLE
Documentation - Deploy 

### ISSUE THREAD

**Issue by rrubio** [vendure-ecommerce/vendure#209]
**Is your feature request related to a problem? Please describe.**
Currently, we run the server from "dev-server" it's great! 

**Describe the solution you'd like**
For production deployment? do we copy "dev-server" and rename it to production?

**Describe alternatives you've considered**
Been trying to run it like a normal nodeJS app, but not having much luck.

**Additional context**

**Comment by michaelbromley** [comment]
> Currently, we run the server from "dev-server" it's great!

Glad you had success with that, but actually the dev server is only intended to be used when developing the Vendure framework core & plugins themselves! 

The recommended way to build a project with Vendure is given in the "getting started" guide: https://www.vendure.io/docs/getting-started/

The advantage of doing it that way is that you don't need to clone the entire Vendure monorepo (which is pretty big and includes lots of build/testing related code that is not needed for a production project).

So I'd recommend you follow the getting started guide, create a new project and then copy your existing code over to the resulting folder structure, because it includes a build step which will output transpiled JavaScript which can then be served for production.

**Comment by rrubio** [comment]
Cool! thank you for clearing that up for me, i was a bit confused :-)

**Comment by rrubio** [comment]
@michaelbromley don't mean to be pest. Creating new plugins - https://www.vendure.io/docs/developer-guide/plugins/writing-a-vendure-plugin/ is this done under the dev-server environment

Would i create new plugins with my own business logic under the newly created project outlined on "Getting Started"? I would also like to add additional queries to shop-api and extend the schema with new columns.

**Comment by michaelbromley** [comment]
You basically never need to use the dev-server unless you are contributing to this repo directly.

To create a plugin you would do that in your newly-created project. The way I structure my projects is like this:
```
dist/
src/
  |- index.ts (etc)
  |-plugins/
      |- some-plugin/
            |- some-plugin.ts
            |- (other files/dirs used by the plugin)
```

> I would also like to add additional queries to shop-api and extend the schema with new columns.
Docs on [extending the GraphQL API](https://www.vendure.io/docs/developer-guide/plugins/#extending-the-graphql-api)

To add new columns, the simplest way is to [add CustomFields](https://www.vendure.io/docs/developer-guide/plugins/#modifying-the-vendureconfig) as part of your plugin. If you require more complex data to be stored than is possible with custom fields, you would need to [define a new TypeORM entity](https://www.vendure.io/docs/typescript-api/plugin/vendure-plugin-metadata/#entities)

I am aware that the plugins system is somewhat under-documented. I plan on creating a "real-world Vendure" repo which includes a fully-featured plugin implementation which demonstrates all of these concepts soon.

**Comment by rrubio** [comment]
Man! thank you, really appreciate you taking the time. It makes total sense.
