### ISSUE TITLE
Draft orders are never placed

### ISSUE THREAD

**Issue by martijnvdbrug** [vendure-ecommerce/vendure#2105]
**Describe the bug**
The order placement strategy is never called for Draft orders, so draft orders are never placed.

**To Reproduce**
1. Create a Draft order
2. Move it to `PaymentSettled`
3. The order has no placedAt date and the OrderPlacedEvent is never emitted

The order placed strategy is never called, because a draft order is never `active`: https://github.com/vendure-ecommerce/vendure/blob/6cf1608d75ac16b05c197349a9771c913f5d3d9c/packages/core/src/service/helpers/order-state-machine/order-state-machine.ts#L199

**Expected behavior**
Draft orders should trigger the same OrderPlacedStrategy as shop-api orders

* Fixing this will also cause order confirmations to be sent for draft orders, is that expected?
* Is there any need for differentiating between Draft order settlement and normal orders? If so we might need to introduce something like `order.isDraft`

**Environment (please complete the following information):**
 - @vendure/core version: 1.9.5
 - Nodejs version 16
 - Database (mysql/postgres etc): MySQL

**Comment by DanielBiegler** [comment]
Just ran into this again when I investigated why orders created from drafts don't show up in the metrics widget.

1. Draft orders are never `active`
2. This leads to drafted orders never being settled for the reason @martijnvdbrug pointed out
3. This means `orderPlacedAt` is `null`
4. This leads to them not showing up in the metric queries because it expects a date

Fixing this issue would allow drafted orders to show up in metric widgets.

**Comment by hrishikeshdkakkad** [comment]
Why is this code still not a part of the `master` branch?
What does the release process look like?

**Comment by michaelbromley** [comment]
> Why is this code still not a part of the master branch?

because nobody yet made the required changes to fix it. 

> What does the release process look like?

We aim for patch releases every 2 weeks or so. Whatever has been fixed in that time window will make it in to that patch release. Most fixes are done by myself, but a significant amount of work is also done by the open source community and since this is open source, users are encouraged to contribute to fixes they want to see released, for the benefit of all :)
