### ISSUE TITLE
(Admin UI) How to add a custom svg icon for a navbar item?

### ISSUE THREAD

**Issue by Stefanyshyn** [vendure-ecommerce/vendure#2111]

**Comment by dlhck** [comment]
This looks like a general support request rather than an issue specifically related to this project. For community support, you are welcome to join our [Discord community](https://vendure.io/community) where you can post your question in the `#help` channel. In case your company needs dedicated support please reach out to us [via our contact form](https://vendure.io/contact).

If you think I've made a mistake and this is indeed an issue specific to this project, please reply and the issue can be re-opened if needed.
