### ISSUE TITLE
AssetServerPlugin: Wrong preview path for SVG mimeType

### ISSUE THREAD

**Issue by Draykee** [vendure-ecommerce/vendure#2172]
**Describe the bug**
For files uploaded in a SVG format a `.png` preview file format is stored.
![image](https://user-images.githubusercontent.com/19676051/237052942-68898a8f-ba5e-453d-9ec3-33058d1255f5.png)

This makes the file rendered in the storefront way bigger then intended and apparently it also takes longer to request, as it needs to get "transformed" tp png first. This has a negative impact on performance scores.

**To Reproduce**
1. Upload a SVG file
2. Use it, or check preview links

**Expected behavior**
The file is returned in the original SVG format

**Environment (please complete the following information):**
 - @vendure/core version: 1.9.5

**Comment by michaelbromley** [comment]
I think the problem here is that the "preview" is generated by using the Sharp library to resize the source image to constrained dimensions. But Sharp only deals with raster image formats, so there is no way for it to "resize" an SVG (which is arguably not even a meaningful operation). So "svg" as a format is not supported by default for dynamic image transformations. You can see this in the [DefaultAssetNamingStrategy](https://github.com/vendure-ecommerce/vendure/blob/cb37b3e0dd9cc6e9b35624f33479f6ca6932455a/packages/core/src/config/asset-naming-strategy/default-asset-naming-strategy.ts#L31) where it defaults all unsupported file formats to "png". This could perhaps be made configurable so you could e.g. choose to default to jpg or webp.

But another solution is that in your storefront, if you encounter an Asset that is an SVG file, just use the "source" property rather than the "preview".
