### ISSUE TITLE
 Unable to locate admin ui file

### ISSUE THREAD

**Issue by rodevandroid** [vendure-ecommerce/vendure#2179]
**Describe the bug**
[AdminUiPlugin] Unable to locate admin ui file: C:\vendure\packages\admin-ui-plugin\admin-ui\vendure-ui-config.json

**To Reproduce**
1. yarn
2. yarn bootstrap
3. yarn build
4. yarn populate
5. yarn start (error this command )

**Operation System**
Windows

**Comment by michaelbromley** [comment]
Hi,
It took a while to get around to this so it's probably that it is outdated. I assume that you are attempting to build this monorepo and run the dev server?

I'm going to close this now since it is more of a support request. If you still need help join our Discord community: https://vendure.io/community 👍
