### ISSUE TITLE
How to add additional features Like SMS and other mutations.

### ISSUE THREAD

**Issue by Soso966** [vendure-ecommerce/vendure#2208]
**Is your feature request related to a problem? Please describe.**
I am new to Vendure system and I can't find a way how you manage creating things not supported/exists in vendure by default as SMS gateway or email gateway.

If I want to create a new mutation for new task how to link it in the backend?

**Comment by mpacary** [comment]
Concerning emails management, you can [tweak or replace the default EmailPlugin](https://docs.vendure.io/typescript-api/core-plugins/email-plugin) at your convenience. Never had to worry about SMS sending but I guess that you could create another plugin as well :arrow_right:  [doc](https://docs.vendure.io/plugins/writing-a-vendure-plugin/)

BTW, I guess that a more appropriate place to ask for such help would be the [Discord server](https://vendure.io/community), as your request is not related to a bug or a core / official plugin feature request

**Comment by dlhck** [comment]
This looks like a general support request rather than an issue specifically related to this project. For community support, you are welcome to join our [Discord community](https://vendure.io/community)](https://vendure.io/community) where you can post your question in the `#help` channel. In case your company needs dedicated support please reach out to us [via our contact form](https://vendure.io/contact).

If you think I've made a mistake and this is indeed an issue specific to this project, please reply and the issue can be re-opened if needed.
