### ISSUE TITLE
[V2.0.0] Can not exit process via `ctrl+c` cause of `BullMQ Worker`

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/vendure#2222]
**Describe the bug**
 [V2.0.0] Can not correct exit process via `ctrl+c` cause of `BullMQ Worker`

<img width="1139" alt="image" src="https://github.com/vendure-ecommerce/vendure/assets/2833251/24da61e5-63d6-4b6b-959a-328a7cc36080">

**Expected behavior**

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.0
 - Nodejs version: 18
 - Database (mysql/postgres etc):mysql

**Additional context**

**Comment by is0utfitters** [comment]
I believe this issue should still be open - the logging occurs correctly without erroring since your initial fix, but the processes still hang, leaving the ports in use etc.  Not sure if this is how you should correct this issue, but I was able to correct the behavior by adding a process.exit(0) after your promise.all in the destroy() method of the BullMQJobQueueStrategy class.  Let me know if you think we should open a new issue with a better description and a new PR.
