### ISSUE TITLE
cant perform update on productservice with sqlite 

### ISSUE THREAD

**Issue by wuichen** [vendure-ecommerce/vendure#223]
**Describe the bug**
trying to do a simple update on existing product gives me an error
**To Reproduce**
`const newProduct = await this.productService.update(ctx, {
			id: '4',
			enabled: false
		});
`
<img width="467" alt="Screen Shot 2019-12-05 at 6 19 09 PM" src="https://user-images.githubusercontent.com/6353587/70226690-375e2b00-178c-11ea-8589-f1e3168a3f88.png">
<img width="1203" alt="Screen Shot 2019-12-05 at 6 19 20 PM" src="https://user-images.githubusercontent.com/6353587/70226703-3deca280-178c-11ea-88cd-c93c1705abe5.png">

**Expected behavior**
should update normally
**Environment (please complete the following information):**
 - 0.61
 - v10.13
 - sqlite

**Additional context**

**Comment by michaelbromley** [comment]
I was able to reproduce this even with MySQL. The issue seems to be that you are passing the ID as a string, whereas the database is expecting an integer. I know the typings say it should be a string, but this is because the `UpdateProductInput` is really generated for the front-end client, which will indeed always be passing a string (ids get stringified at the API layer).

So the solution for now is to cast it to any and see if that works for you.
