### ISSUE TITLE
After `addItemToOrder` as a Guest the `activeOrder` is null

### ISSUE THREAD

**Issue by aleBurgos** [vendure-ecommerce/vendure#228]
**Describe the bug**

After `addItemToOrder` as a Guest the `activeOrder` is null. 

**To Reproduce**
1. The store-api is using tokenMethod: 'bearer'
```json
"authOptions": {
        "sessionSecret": "s9f3a242jv",
         "tokenMethod": "bearer",
        "requireVerification":false,
    }
```
2. As a Guest I add a new Item to the order
```
mutation {
  addItemToOrder(productVariantId: 1, quantity: 1 ){
    id
    code
    state
    active
    subTotal
    total
     }
}

```
Response  (every time I add a new item, a new Order is created):
```json
{
  "data": {
    "addItemToOrder": {
      "id": "9",
      "code": "GS9W53EYT5ZLARYT",
      "state": "AddingItems",
      "active": true,
      "subTotal": 3400,
      "total": 3400
    }
  }
}
```
3. But later when I want access to currentOrder:
```
query {
	activeOrder {
            code  
     }
}
```
the result is:
```json
{
  "data": {
    "activeOrder": null
  }
}
```

**Expected behavior**

Be able to access to the order using `activeOrder()` , `order(id)` or `orderByCode(code)`.
After add a new item at the order it should not create a new Order, just add them to the current order.

**Environment (please complete the following information):**
 - @vendure/core version: 0.6.5
 - Nodejs version v10.16.3
 - Database (mysql/postgres etc): MariaDB

I'm not 100% sure if this behaviour is by design. If that is the case what you recommend to implement this escenario in the storefront?

**Comment by michaelbromley** [comment]
Hi there,

When using the `bearer` token method, a token will be issued upon executing the `addItemToOrder` mutation. It is then up to you to include that token in your subsequent request headers so that Vendure knows that you have an existing session. This is described here: https://www.vendure.io/docs/developer-guide/authentication-and-sessions/#bearer-token-sessions

Please let me know if those instructions are not sufficient to resolve the issue.

**Comment by aleBurgos** [comment]
Hi @michaelbromley thanks for the reply! Yes I got it, this solve the issue

Thanks!
