### ISSUE TITLE
How importProducts mutation works?

### ISSUE THREAD

**Issue by aleBurgos** [vendure-ecommerce/vendure#231]
I'm curious to know how this method works, and which format must be the csv file and if this method also support  assets.

Thanks in advance.

**Comment by michaelbromley** [comment]
Hi,

This feature is kind of experimental and the format is undocumented but you can see an example of it here: https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/e2e/fixtures/product-import.csv

The asset paths are relative to the directory configured by `config.importExportOptions.importAssetsDir` (i.e. already residing on the server).

The same format is used in all the e2e tests to populate test data, so it will probably not change much. I'm just not sure about the best method for supporting imports via the GraphQL API yet - and I'd like to eventually support posting assets directly rather than requiring them to already be uploaded to the server beforehand.

**Comment by aleBurgos** [comment]
great! Thanks @michaelbromley !
