### ISSUE TITLE
Proper URLs

### ISSUE THREAD

**Issue by Zyles** [vendure-ecommerce/vendure#235]
**Is your feature request related to a problem? Please describe.**

Remove /category/ and /product/ in URLs and stop using ID numbers.

Wordpress figured this out 10 years ago, don't bring in bad habits.

**Describe alternatives you've considered**

There is none.

**Additional context**

URLs should be permanent, unique and have no ID numbers. The system should not need to distinguish a page, category or product using the url. That should be handled by the API router.

**Comment by michaelbromley** [comment]
Hi,

Are you referring to the demo storefront at https://demo.vendure.io/storefront/? If so, this is just a very basic demo app and is not part of the Vendure server itself. But I do take your point - there are better ways to handle the URLs.

In Vendure a Product has a `slug` field which can be used as a lookup, which can allow "proper" URLs as you suggest. The IDs are still used in the demo storefront just because I built it before the slug functionality was completed, and have yet to update it.

**Comment by Zyles** [comment]
Yes. You are also suffering from the same problems as saleor by having SEO duplicate content issues:

https://github.com/mirumee/saleor-storefront/issues/554

**Comment by michaelbromley** [comment]
Ok, thanks for the pointer. I'll close this as the issues are related to the storefront implementation, which is not a direct concern of this repo.
