### ISSUE TITLE
Duplicate breadcrumb in collection page

### ISSUE THREAD

**Issue by wpplumber** [vendure-ecommerce/vendure#2350]
### Describe the bug
For a better UX I think one breadcrumb is best.

### To Reproduce

Go to [live demo](https://demo.vendure.io/admin/catalog/collections/2?contentsPage=1)
See the attached screenshot.
![image](https://github.com/vendure-ecommerce/vendure/assets/52907282/d537117a-e855-4721-bec5-6bdc92dbfe85)

### Expected behavior
Having one breadcrumb.

 @michaelbromley, I want to work on this.

**Comment by michaelbromley** [comment]
Hi, the two breadcrumbs are showing 2 different things. The top breadcrumb shows your location in the admin ui app. The lower one shows the breadcrumb of the current collection in the collection tree.

Maybe we can represent this latter one better? But we do still want to keep that info. I'm open to suggestions to improve this.

**Comment by wpplumber** [comment]
Welcome, Michael.

> The lower one shows the breadcrumb of the current collection in the collection tree.

Is there a case in this page where there is collection, sub-collection, sub-sub-collection?

Also there is a translation button in this page! is that a bug?

**Comment by michaelbromley** [comment]
Yes, the lower breadcrumb supports deeply-nested paths:
![image](https://github.com/vendure-ecommerce/vendure/assets/6275952/612600fb-75cb-49c8-b835-099a9e23dca2)

> 
Welcome, Michael.

The lower one shows the breadcrumb of the current collection in the collection tree.

Is there a case in this page where there is collection, sub-collection, sub-sub-collection?

> Also there is a translation button in this page! is that a bug?

No, that's intentional so that you can switch to different language versions of the collection.
