### ISSUE TITLE
Does Vendure supports gracefully shutdowns?

### ISSUE THREAD

**Issue by Zizitto** [vendure-ecommerce/vendure#2474]
https://cloud.google.com/run/docs/samples/cloudrun-sigterm-handler

Our Vendure server is deployed via Cloud Run, worker is deployed via Kubernetes.

Both deployments from time to time receive SIGTERM signals. (during deployment of some changes or scale-downs).

Looks like HTTP requests and jobs processing are terminating immediately, which causes data inconsistency issues.

Can somebody check if Vendure supports gracefully shutdowns?

**Comment by michaelbromley** [comment]
Hi,

Since Vendure is built on NestJS, it handles graceful shutdowns the same way, described here: https://docs.nestjs.com/fundamentals/lifecycle-events#application-shutdown

The specific issue of requests being terminated is discussed in this issue: https://github.com/nestjs/nest/issues/11416 - it seems like it is something that needs to be addressed in NestJS itself.

As for jobs that are being processed - here's what happens:

1. The `onModuleDestroy()` hook [here](https://github.com/vendure-ecommerce/vendure/blob/20978e9b5ee6176166d3dc82f9b4d7e18e6d89c1/packages/core/src/job-queue/job-queue.service.ts#L62) is called, which invokes and awaits `stop()` on all running job queues. 
2. This in turn calls the [stop() method](https://github.com/vendure-ecommerce/vendure/blob/a92d95bb0572301b74e48622a32df48b15c05ef1/packages/core/src/config/job-queue/job-queue-strategy.ts#L43) of the configured JobQueueStrategy. This can therefore be configured to the desired behaviour. The default strategy in the DefaultJobQueuePlugin, for instance, will execute [this logic](https://github.com/vendure-ecommerce/vendure/blob/0441a0338aeb7742012e24594feb67935d09b2fc/packages/core/src/job-queue/polling-job-queue-strategy.ts#L154) that waits 2 seconds for running jobs to complete.

**Comment by dlhck** [comment]
This looks like a general support request rather than an issue specifically related to this project. For community support, you are welcome to join our [Discord community](https://vendure.io/community)](https://vendure.io/community) where you can post your question in the `#help` channel. In case your company needs dedicated support please reach out to us [via our contact form](https://vendure.io/contact).

If you think I've made a mistake and this is indeed an issue specific to this project, please reply and the issue can be re-opened if needed.
