### ISSUE TITLE
ListOptions Date parameter

### ISSUE THREAD

**Issue by Szbuli** [vendure-ecommerce/vendure#251]
**Describe the bug**
Using ListOptions with date filter creates db error.

The unit tests expect the datetime input to be a string like "2012-02-02" but it is invalid. Only full datetime inputs are valid like "2012-02-02T02:02:02.000Z".

The unit tests also expect the value to be a string, but it is a date object in reality.

The database error is because typeorm does not do any data type conversion for select parameters. This causes the input parameters to be an invalid string (as only to string is called, not toIsoString).

**Comment by michaelbromley** [comment]
I have reproduced this behaviour. The query log for a date-filtered query looks like this:

```log
debug 1/29/20, 16:35 - [TypeORM] Query: "SELECT <... snip ...> WHERE "order"."createdAt" > ?" -- [Tue Dec 31 2019 11:10:10 GMT+0100 (Central European Standard Time)]
```

Strangely, the query sort-of works with MariaDB, which is probably why I never noticed it (I usually develop against MariaDB).

**Comment by Szbuli** [comment]
I do not know why typeorm is not transforming input parameters in a select... Every database might have a different input format for dates...

**Comment by michaelbromley** [comment]
I know, it's strange. I tested with sqlite, mysql & postgres drivers and in each case the query looks the same (apart from minor db-specific syntax like placeholders in postgres). 

The weird thing is that the WHERE clause works perfectly as-is with postgres. I ran the dev server with postgres and traced a query with a Date param. TypeORM passes the JS Date object all the way through to the underlying DB driver (the `pg` package in this case). The `pg` package happens to have code to detect JS Date objects in parameters and convert them into the correct format for Postgres.

On the other hand, it looks like the `sqlite3` driver performs no such conversion, and presumably the same with mysql.

I'm surprised there are not more issues on the TypeORM repo about this - it's really confusing. Needs a bit more work but at least we're getting closer to a solution!

**Comment by michaelbromley** [comment]
I've created an e2e test suite so that the ListQueryBuilder filtering can be tested across DBs. I have found that the tests pass with MariaDB and Postgres, and fail with SQLite.

I have confirmed that the `mysql` and `pg` packages do their own Date -> string conversions, but it appears `sqlite3` does not. Indeed, for `sql.js` (which is used by the e2e tests), there is even an open issue to add this functionality: https://github.com/kripken/sql.js/issues/334). 

In the TypeORM repo there is also an open issue (https://github.com/typeorm/typeorm/issues/2694) related to this problem in SQLite.

Presumably the SAP HANA package `@sap/hana-client` also does not perform date conversion, though I cannot verify since it seems to be closed source.

### Solution

Since we cannot rely on the various driver packages to always convert JS Date objects, we should perform the conversion ourselves inside the `ListQueryBuilder`. We must ensure the format will be accepted by all drivers:

#### postgres
> 8.5.1. Date/Time Input
Date and time input is accepted in almost any reasonable format, including ISO 8601, SQL-compatible, traditional POSTGRES, and others. 

https://www.postgresql.org/docs/9.1/datatype-datetime.html

#### mysql
> A DATETIME or TIMESTAMP value can include a trailing fractional seconds part in up to microseconds (6 digits) precision. In particular, any fractional part in a value inserted into a DATETIME or TIMESTAMP column is stored rather than discarded. With the fractional part included, the format for these values is **'YYYY-MM-DD hh:mm:ss[.fraction]'**

https://dev.mysql.com/doc/refman/8.0/en/datetime.html

#### sqlite
> A time string can be in any of the following formats:
YYYY-MM-DD
YYYY-MM-DD HH:MM
YYYY-MM-DD HH:MM:SS
YYYY-MM-DD HH:MM:SS.SSS
YYYY-MM-DDTHH:MM
YYYY-MM-DDTHH:MM:SS
YYYY-MM-DDTHH:MM:SS.SSS
HH:MM
HH:MM:SS
HH:MM:SS.SSS
now
DDDDDDDDDD

https://www.sqlite.org/lang_datefunc.html

#### SAP HANA

> Supported formats for TIMESTAMP
YYYY-MM-DD HH24:MI:SS.FF7

#### Conclusion

The common format from my research for datetimes appears to be:

`YYYY-MM-DD HH:MM:SS.SSS`
