### ISSUE TITLE
HttpHealthIndicator is marked as a scoped provider, causing the server to not start up with the usage of the HttpHealthCheckStrategy

### ISSUE THREAD

**Issue by sidings** [vendure-ecommerce/vendure#2617]
**Describe the bug**
The `HttpHealthCheckStrategy` uses the `HttpHealthIndicator` provided by the `@nestjs/terminus` package. When using the `HttpHealthCheckStrategy` as one of the application health checks, the server fails to start up and throws an error:
```
InvalidClassScopeException [Error]: HttpHealthIndicator is marked as a scoped provider. Request and transient-scoped providers can't be used in combination with "get()" method. Please, use "resolve()" instead.
```
This wasn't happening when I was using Vendure version 1.9.5, but is now happening when I'm on version 2.0.4.

**To Reproduce**
1. Add the following to the `vendure-config.ts` file. 
     ```
     systemOptions: {
    healthChecks: [
      new HttpHealthCheckStrategy({
        key: 'admin-ui-probe',
        url: <URL>,
      }),
    ],
3. Start the server.
5. See error in the logs.

**Expected behavior**
I expect the server to start up properly and the health check to be initialized.

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.4
 - Nodejs version: 18
 - Database (mysql/postgres etc): Postgres

**Additional context**
Add any other context about the problem here.

**Comment by michaelbromley** [comment]
OK I found a couple of issues going on here:

1. First of all, we were using the `injector.get(HttpHealthIndicator)` method but NestJS requires the use of `injector.resolve(HttpHealthIndicator)` in this case. That was probably an API change that I didn't notice in one of the updates.
2. But resolving that issue exposed a deeper issue: due to internal changes in some earlier NestJS versions, the `HttpHealthIndicator` depends on the `@nestjs/axios` and `axios` packages being installed, and the `HttpModule` being imported into the core.

Since I don't really want to add 2 new dependencies for this single case (which is probably quite rarely used), I will create a custom health indicator which has no new dependencies for the next patch version.
