### ISSUE TITLE
Service Booking / Rental Marketplace

### ISSUE THREAD

**Issue by svallory** [vendure-ecommerce/vendure#2633]
Hi, I'm new to Vendure and I'm evaluating it for a client which is about to launch a Therapy marketplace similar to BetterHelp but in Brazil. I've been looking through the documentation but couldn't find instructions or anything that made me sure a service booking marketplace is doable with reasonable effort

The goal of this issue is actually to assess how this could be achieved and how much effort it would take. We should have finished the project already but issues with Sharetribe's pay-to-code-it-yourself policy prevented us from doing so.

If Vendure customization shows itself as a viable solution in this time constraint, You guys can expect a series of contributions to the source code. I initially thought of making this via a plugin (maybe even a paid one), but I think it would be better to natively support this.

## Describe the solution you'd like

The Service Booking and Rental marketplaces as very similar. Ideally, to support this model, I believe at least the following features need to be supported:

- [ ] Listings with time-slot based stock 
- [ ] Sellers can set available time slots on a per-offer basis
- [ ] Sellers (or at least the admin) can set a time based cancellation policy
- [ ] Sellers only get paid after the appointment or rental period

Additional features that are also important but not strictly necessary include:

- [ ] Calendar synchronization
- [ ] Seller can configure automatic booking or require it to be approved
- [ ] Customers can rate the seller service

**Describe alternatives you've considered**
Using sharetribe

**Additional context**

There are lots of other things that can be done to serve theses use cases, but it may be worth to think strategically here and check if a customizable transaction process isn't the best way to go about this. Sharetribe calls this a [transaction engine](https://www.sharetribe.com/features/transaction-engine/). Combined with custom fields and the Strategies architecture of Vendure it would allow clients to setup any kind of marketplace they want. Btw, kudos on the Strategy pattern use! In fact the entire architecture of Vendure is a work of art.

<img width="1812" alt="image" src="https://github.com/vendure-ecommerce/vendure/assets/117560/67b2c0fa-54a7-4e58-95ee-03935458efbd">
 
I've evaluated a lot of marketplace solutions for this project and I can say that adding this kind of flexibility would make Vendure the best marketplace solution by far!

**Comment by michaelbromley** [comment]
Hi!

Thanks for the detailed and clear information, and for your kind words about Vendure's design :)

First of all, I can confirm that it is indeed possible to build service booking & rental apps with Vendure. For example, https://fainin.com is a local rental marketplace built with Vendure. We also have https://www.swile.co who sell event tickets through Vendure.

But let's look at what it involves, so that you can get a better idea about whether it's the right fit for the constraints of your current project:

> Listings with time-slot based stock
 Sellers can set available time slots on a per-offer basis
 Sellers (or at least the admin) can set a time based cancellation policy

Caveat: without in-depth knowledge of your domain model and time to thoroughly consider this, here are my initial thoughts. 

- You can define a [custom entity](https://docs.vendure.io/guides/developer-guide/database-entity/) to model an `Offer` based on available time slots, which could be implemented as custom fields on the ProductVariant entity.
- Time-slot based stock is sufficiently far-removed from the usual concept of stock keeping that I'd probably recommend implementing a custom system.

> Sellers only get paid after the appointment or rental period

The [order process](https://docs.vendure.io/guides/core-concepts/orders/#custom-order-processes) is highly configurable, so you could e.g. define an order state of `RentalStarted` after which a transition to a `RentalConcluded` could automatically trigger the payment capture via a [`onTransitionEnd()` state transition hook](https://docs.vendure.io/guides/core-concepts/orders/#responding-to-a-state-transition).

---

I _would_ advise that this functionality be implemented as a plugin. My approach to the core is that I want to provide:

1. All typical functionality that covers 80% of ecommerce needs
2. The low-level APIs which enable devs to build out the remaining 20% that is unique to their business.

In this way, the core stays lean and building a Vendure app is more of an additive process (build only what you need) rather than subtractive (remove all the stuff that isn't applicable).

Of course, we also want to make it so that devs building that remaining 20% need only do as much work as needed. That's where plugins come in. My goal is that _everything_ can be implemented as a plugin. If not, then maybe we need a core API change/extension. If so, then either we build it, the community builds it, or the developer builds it.

**Comment by svallory** [comment]
Hey @michaelbromley, feel free to close this issue. The client did not have the funds to for the project.
