### ISSUE TITLE
OrderByCodeAccessStrategy and DefaultOrderByCodeAccessStrategy are not exported

### ISSUE THREAD

**Issue by floze** [vendure-ecommerce/vendure#2664]
OrderByCodeAccessStrategy and DefaultOrderByCodeAccessStrategy are not exported from core, is this intentional? If I would want to simply configure `anonymousAccessDuration` I couldn't import the default strategy...

**To Reproduce**
1. import { DefaultOrderByCodeAccessStrategy } from '@vendure/core';
2. fail

**Expected behavior**
OrderByCodeAccessStrategy and DefaultOrderByCodeAccessStrategy should be available from the core.

**Environment (please complete the following information):**
 - @vendure/core version: v2.1.6

**Comment by michaelbromley** [comment]
Hi,

It's not intentional, just an oversight. Would you like to PR to `master` to fix this? You'd need to add the exports to [this file](https://github.com/vendure-ecommerce/vendure/blob/066e5247094ba2fa0433a8ade85edd6a398a8d17/packages/core/src/config/index.ts#L54).

In the mean time you can still import them via a deep import, i.e. `@vendure/core/dist/config/order/order-by-code-access-strategy`

**Comment by floze** [comment]
Sure, I created a pull request #2692
