### ISSUE TITLE
Introduce Sync event subscribing option

### ISSUE THREAD

**Issue by seminarian** [vendure-ecommerce/vendure#2735]
**Is your feature request related to a problem? Please describe.**
I would like to share my experiences regarding Vendure Events. https://docs.vendure.io/guides/developer-guide/events/

I totally love the idea/concept of all the Events which are currently supported by the Vendure Core.

Currently the Events are only dispatched after the original transaction (in which they were dispatched) is completed.
Out of the box we don't have a way of knowing if the code actually executed.

Examples:
Something goes wrong while processing the Event.
A server/pod restarts while processing the Event.

This is a huge problem to us and makes us not want to use any of those Events because they basically don't offer any guarantees.
This is a huge loss since we miss out on all the potential these Vendure Events have to offer us.
We have encountered issues like this in production.
In past projects I've had to build control-mechanisms by storing extra data in the database and scripts which check if Events actually got executed.

Vendure is an awesome project though I really believe this issue right here should be tackled asap so the event system can be production-worthy.

**Describe the solution you'd like**
I would love to see the option, when subscribing to events, to provide a setting which indicates if the event should be dispatched:
Synchronously (within the same transaction) during journey of request to response
Asynchronously (Like it is now) after the transaction has finished and the request has been served

**Desired usecase**
The reason I bring this up is that we're trying to build a reliable system, which hooks into some events dispatched by Vendure Core.

Our vision:
Extract any logic/features inside the currently configured Event Listeners to Job Queue workers.

We would only use the Synchronous Events to hook into certain occurences in which the only task that happens is adding a job to the queue. We can add a delay to the job processing to make sure the transaction has been comitted before the job is being processed.
We would wrap this in a try/catch (and proper timeout) which would log/alert us if adding a job failed. We could build this as a self-healing system.

We would never add state to the jobs. Only references to ids.
This for the odd case where adding to the queue worked but something else goes wrong and the transaction fails. 

This would result in a very reliable/observable system which is super extensible by leveraging all the Vendure Events.

**Additional context**
Reply from Michael on Discord:
Thanks for the detailed write-up. Yes, certainly transfer this to a GH issue to others might find and comment.

I do like the idea of being able to opt-in to sync behaviour. The reason the async, wait-for-transaction behaviour is there currently is that it was a common source of bugs that people would consume events and run into issues with data isolation due to ongoing transactions that were basically race conditions.

Opting-in to sync handling means you know the risks and are deciding to mitigate them in some other way, like you mention.

I'm just looking at the EventBus code now and implementing a sync API would actually be extremely simple: 
```
ofTypeSync<T extends VendureEvent>(type: Type<T>): Observable<T> {
  return this.eventStream.asObservable().pipe(
            takeUntil(this.destroy$),
            filter(e => e.constructor === type),
            filter(notNullOrUndefined),
        ) as Observable<T>;
}
```
It would even be possible for you to prototype this approach already by accessing the private eventStream property with an (as any) assertion and implementing the above.

a nicer API would probably be
```
ofType(SomeEvent, {
  awaitRunningTransactions: false,
})
```

or something to that effect.

**Comment by seminarian** [comment]
I tried the suggested code-change:
The events are indeed processed before a reponse is returned. Though when I throw an error I would hope that the error is returned via the GraphQL api.
Currently the process crashes:

```
/home/pieter/projects/vendure-app/src/plugins/collections-variants-calculations/collections-variants-calculations.plugin.ts:68
        throw new Error('Not implemented')
              ^
Error: Not implemented
    ...
    at CollectionService.create (/home/pieter/projects/vendure-app/node_modules/@vendure/core/src/service/services/collection.service.ts:470:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OVerrideCollectionResolver.createCollection (/home/pieter/projects/vendure-app/src/plugins/collections-variants-calculations/api/override-collection.resolver.ts:41:22)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
pieter@Freedoms:~/projects/vendure-app$ 
```

The fact that it does not have the power to break the transaction in which the original event was dispatched makes it unreliable again. No guarantees if that code got actually executed succesfully or not. We only know that it tried to execute it.

Would be awesome if somehow any error thrown in the handlers would be handled as if it's thrown from where the event was dispatched.

**Comment by seminarian** [comment]
This version of code got tested:
```
    /**
     * @description
     * Publish an event which any subscribers can react to.
     */
    async publish(event) {
        this.eventStream.next(event);
        const syncHandlers = this.syncEventHandlers.get(event.constructor);
        for (const handler of syncHandlers || []) {
            await handler(event);
        }
    }

    handleSync(type, handler) {
        const handlers = this.syncEventHandlers.get(type);
        if (handlers) {
            handlers.push(handler);
        } else {
            this.syncEventHandlers.set(type, [handler]);
        }
    }
```
With this change we will need to await publish calls in the code-base.

Discord thread: https://discord.com/channels/1100672177260478564/1217054934508245033


Ideally I would like to see a way to order handlers.

It's mainly about separation of responsibilities:

E.g.:
A Product gets updated
-> We have a sync event listener which will update a custom field PriceBeforeDiscount
-> We have a sync event listener which will add the update-search-index job for that product, we want this one executed as last, always, so the final data is put in the index. (We have a modified verson of ElasticSearchPlugin so we have control over these events)

OR We could bypass this with installing one Sync Event listener which combines logic from different plugins.

**Comment by seminarian** [comment]
Turns out that the plugins array order does not have an effect on `onApplicationBootstrap` execution order.

I first considered wrapping the `handleSynce` call in a `setTimeout` of 50ms , that makes sure it's registered last so it's being invoked last. It worked but seems brittle as well.

For now, I've registered all syncHandlers in `onModuleInit` and the ES plugin syncHandlers in `onApplicationBootstrap`

Some more context from the discord thread:
![image](https://github.com/vendure-ecommerce/vendure/assets/9881519/60617776-6d7b-4d5a-b1ab-f164b11fdcec)

**Comment by michaelbromley** [comment]
Some notes on the design of this feature:

### Prior Art

I came across this thread on event handling in C# which seems to work like this:

- [Is the C# EventHandler designed the wrong way?](https://softwareengineering.stackexchange.com/questions/405849/is-the-c-eventhandler-designed-the-wrong-way)
- [Are C# events synchronous?](https://stackoverflow.com/questions/7106454/are-c-sharp-events-synchronous)

From the latter link:

> This is a general answer and reflects the default behavior:
>
> 1. Yes, it blocks the thread, if the methods subscribing to the event are not asynchronous.
> 2. They are executed one after the other. This has another twist: If one event handler throws an exception, the event handlers not yet executed will not be executed.

### Risks

A blocking event handler introduces a point of risk into the system, because a handler might:
- **throw**, in which case the triggering code will fail (e.g. a mutation to update a product will fail and changes in the transaction will be rolled back)
- **be slow**, in which case the API response will be blocked.

The first risk is a design choice - the point of this API is to carry out tasks that _must_ succeed, and if they don't succeed, we consider the whole transaction to be void. In this regard, the behaviour is correct, albeit must be used with caution.

The second risk (speed) is something we can take steps to minimize. For example we can time the execution of individual handlers at runtime and issue warnings when they exceed a certain threshold of e.g. 100ms.

### Order of execution

It can be desirable to be able to specify order of execution for blocking handlers. To do this we would have to assign a unique id string to each handler, and then provide a means of specifying execution before or after another known handler, referenced by id.

We would debug log this info to ease development.

### API Changes

In order to correctly implement this, the call to `EventBus.publish()` signature will have to change to return a promise. Everywhere we use it in the core will have to have `await` added, and we'll need to update the docs to reflect this new usage.

It is not strictly a breaking change, since for all existing observable-based event handlers, the async nature makes no difference.

### Naming

I've not yet settled on a name for the new blocking handler method. Ideally it should communicate the fact that it is blocking. I'll research any existing APIs for ideas.
