### ISSUE TITLE
Finite order status naming convention should be altered.

### ISSUE THREAD

**Issue by itsgauravjain22** [vendure-ecommerce/vendure#274]
**Is your feature request related to a problem? Please describe.**
The below order status naming convention would really confuse a business person as well as customer. These default status should be more concise and yet understandable.

```
export type OrderState =
    | 'AddingItems'
    | 'ArrangingPayment'
    | 'PaymentAuthorized'
    | 'PaymentSettled'
    | 'OrderComplete'
    | 'Cancelled';
```

I even don't understand what does adding item would do. If it signify that product has been added to order, I guess, it's not a significant order status to be visible to admin user. Similar is said for arranging payment.

**Describe the solution you'd like**
Coming from woocommerce environment, I would suggest the following order status naming convention where appropriate:

```
Pending Payment
Cancelled
Failed
Processing
On Hold
Shipped
Completed
Refunded
```

These are the woocommerce order statuses, I use it on daily basis. They abstract the underlying phenomena in store and just reflect the key highlights of order.

As the names are descriptive enough, Following link would help understand the functioning of system for each status.
https://docs.woocommerce.com/document/managing-orders/

It would be beneficial to understand other successful ecommerce platforms while planning the feature.

**Comment by michaelbromley** [comment]
It sounds like the WooCommerce system works slightly differently to Vendure. In Vendure, as soon as you add an item to your cart, an Order has been created, and that order is in the state `AddingItems`. The whole process is described here: https://www.vendure.io/docs/developer-guide/order-workflow/

I agree that it would probably not be that useful (most of the time) for an Admin user to be able to see orders in the `AddingItems` and `ArrangingPayment` states. The default should probably be to show the orders that are in the `PaymentAuthorized` or later states in the order list view.

So the problem seems more like a UX one rather than the inherent naming of the states - which is after all an internal implementation detail.
