### ISSUE TITLE
@Override decorator for overriding methods in core services

### ISSUE THREAD

**Issue by pevey** [vendure-ecommerce/vendure#2774]
This question has come up before, and it is also something I'm running up against now.

In Java, there is the @Override decorator for overriding methods in superclasses.  There is no similar built-in concept in Javascript or Nestjs.

I found this Github issue for Nestjs that describes a way someone created and added an @Override decorator. https://github.com/nestjs/nest/issues/3457

Is this something we might want to add to Vendure core to make it possible for plugins to override certain parts of core services?  

It's not the ideal way to make the vast majority of customizations, but sometimes it might be necessary.  For instance, I am still banging my head against the wall a bit on the best way to achieve some inventory process changes I want to make, where the currently available injectable strategies are just not enough.

**Comment by michaelbromley** [comment]
Hi Lacey,

Looking at that overide decorator, it seems to be solving a slightly different problem: how to avoid duplication of decorators on methods your are overriding.

Since Vendure core service methods do not use decorators, that's not a concern here.

But as to the overall point of how to override core service methods: I agree that it is something that is worth supporting with the _strong_ caveat that as soon as you override a core method, you are creating potential tech debt and your app will be more vulnerable to upgrade-related bugs.

In terms of implementation, my first thought is to whether we could make use of the NestJS DI container to do this. Code sketch:

```ts

class MyCustomProductService extends ProductService {
  override findOne(...) {
    // some custom impl
  }
}

// in Vendure Config 

export const config: VendureConfig = {
  // ...
  systemOptions: {
    serviceOverrides: [{ provide: ProductService, useClass: MyCustomProductService }],
  }
};
```

**Comment by pevey** [comment]
Here is an example of overriding a core service in another system I worked on: https://github.com/pevey/medusa-auth-cognito/blob/main/src/services/auth.ts

This goal in that case was to override to core auth service to enable using AWS Cognito as a third-party authentication provider.

In their API, you had to put service additions/overrides in a specific folder within the project, and those were then processed by the loader.  You can see in the example how I imported the default service as a different name, extended it, and exported it as the AuthService, to override the original.

This approach does have some drawbacks.  It's a little wild west.  But it does have the advantage of not needing a config file entry.

It would be great if Vendure had an API somewhere in between, I think.  Where the explicit override is done in perhaps the plugin configuration and not the project configuration. 

```ts
@VendurePlugin({
	imports: [PluginCommonModule],
	providers: [MyAuthService],
	overrides: [{ service: 'AuthService', useClass: 'MyAuthService'}]
	...
```

I can imagine that services and possibly strategies might have use cases to be overridden.  I don't think entities should be overridden in this way since there is already an API for that.

**Comment by pevey** [comment]
When loading the plugins, Vendure could print a warning if there are conflicting overrides on the same resources.

**Comment by michaelbromley** [comment]
Yes I agree this would make more sense as part of the plugin metadata.

I wonder if we could do it without even adding a new "overrides" property, but by using the "providers" array (since conceptually we will be re-defining a provider)

Something like

```ts
@VendurePlugin({
	imports: [PluginCommonModule],
	providers: [override(AuthService, MyAuthService)],
})

**Comment by pevey** [comment]
An additional thought: If we were to create a new decorator, `@Override`, and use this for any service classes intended to override core services of the same name, perhaps we would only need to include the class in the list of providers exactly as is done now.  Nothing more.

That decorator could trigger the same logic as the config would: replace the existing service of the same name with this service.

For instance:

``ts
import (AuthService as VendureAuthService } from '@vendure/core'

@Override
export default class AuthService extends VendureAuthService {
	super()
	...
}
```

One other DX issue with extending core classes now is the fact that properties of the services are private.  For instance, in one example, I extended the history service in order to have a new type of history timeline for a complaint detail page.  For this use, I only needed the additional history service functionality within the plugin, so I could get away with extending, but not overriding.  It looked like this:

```ts
export class ComplaintHistoryService extends HistoryService {
	constructor(
		private myConnection: TransactionalConnection,
		private myAdministratorService: AdministratorService,
		private myListQueryBuilder: ListQueryBuilder,
		private myEventBus: EventBus,
  ) {
		super(myConnection, myAdministratorService, myListQueryBuilder, myEventBus)
  }

	async getHistoryForComplaint(
	...etc
```
If the connection, eventbus, etc properties had been protected instead of private, I wouldn't have needed to do the clunky workaround.  I could have just accessed them as this.connection, etc.

**Comment by pevey** [comment]
I like the idea of the decorator if I can figure it out, since Vendure/NestJS already makes heavy use of decorators.  I think it would make the DX feel more consistent and have less cognitive load, since no need to remember the syntax of the configuration.

**Comment by michaelbromley** [comment]
Yes the decorator approach is also elegant.

I assume that:

- It would implicitly add the `Injectable()` decorator? A bit like the current `Resolver()` decorators also implicitly makes the class injectable.
- It figures out what class to override based on the inheritance?

**Comment by pevey** [comment]
I think to make the ServiceCoreModule take in the overrides stashed in config, the ServiceCoreModule will need to be made a Dynamic Module, very similar to the PluginModule.  The ServiceModule wrapper will then need to import ServiceCoreModule.forRoot().

Please let me know if any of this seems off-base to you before I get going on it.

**Comment by michaelbromley** [comment]
Hi,

Yes, your breakdown of the problem sounds right to me. `getServiceOverridesFromPlugins()` to get the overridden classes and pass as the providers array in the ServiceCoreModule.

One issue I thought of:

### Multiple overrides of the same class

If we use an `@Override()` decorator on the class, then I think we can only have a single override at a time. So if 2 plugins override the same service, then the last one processed will win, and the other will be ignored.

We can e.g. display a warning when a service is overridden more than once, but that still would leave a situation where certain combinations of plugin would be fundamentally incompatible.

This may be too much of an edge-case to worry about, but since some services are rather large, the chance that 2 plugins want to override just _one_ method of that service is a possibility.

Two possible solutions to this:

1. Plugins need to be explicit about what internal services they override. If Plugin A overrides `ProductService.findOne()`, and Plugin B wants to override `ProductService.findAll()`, then Plugin B could override Plugin A's `ProductService` rather than the core one. 
2. We allow multiple overrides to co-exist with some kind of dynamic delegation which allows a particular override to be responsible for only those methods that it actually defines. This is a lot more complex but way better for composition.

**Comment by pevey** [comment]
Per Discord discussion, I'm closing this issue for now. We may want to revisit this at a later date, but overriding core service methods could create unpredictability as Vendure plugin ecosystem grows.  Where existing core services are too rigid for certain use cases, we should first try to create new injectable strategies to provide greater flexibility.  For my current use case, I will focus on https://github.com/vendure-ecommerce/vendure/issues/2725.
