### ISSUE TITLE
Implement relational structured data in custom fields

### ISSUE THREAD

**Issue by arbughiu** [vendure-ecommerce/vendure#2913]
**Is your feature request related to a problem? Please describe.**
I am working on a pet food store (yes, really). I would like to be able to attach structured and relational data for my products. For example, I would like to be able to provide a table with two columns (ingredient name and composition percentage), instead of writing this data in an unstructured manner in the description.

<img width="701" alt="image" src="https://github.com/vendure-ecommerce/vendure/assets/11235104/8f744985-5f6c-435d-8151-5f0110336b61">

**Describe the solution you'd like**
It would be great if the Admin UI could allow to provide custom components not just for custom fields but also for entities. (something similar to what is discussed here https://docs.vendure.io/guides/extending-the-admin-ui/custom-form-inputs/#custom-field-controls-for-relations) 

**Describe alternatives you've considered**
For now, I have implemented a hack consisting of a component that saves my data as stringified JSON. However, although this does the job, there are negative implications to having the data unstructured.

**Additional context**
The original thread where this feature was discussed and requested: https://discord.com/channels/1100672177260478564/1252882486342582353

**Comment by michaelbromley** [comment]
### Idea: `Struct` custom field type

I've had this idea for a while: a new type for custom fields which is named "struct". The naming open for debate - there might be a better word like "object" or something. Anyway, I'll use "struct" for now.

It would be defined like this:

```ts
const config = {
    // ...
    customFields: {
        Product: [
            {
                name: 'composition',
                type: 'struct',
                fields: [
                    { name: 'ingredient', type: 'string' },
                    { name: 'compositionPercentage', type: 'float' },
                ],
            },
        ],
    },
};
```

When using the `struct` type, you are then required to define the `fields` array, which specifies the properties on that struct.

The `fields` would be like a subset of the custom field definition, allowing only primitive types: `string`, `text`, `int`, `float`, `datetime`, because internally this will get serialized into a JSON string.

It will **not support** localized strings or relation types, as these cannot easily be serialized into a JSON string.

It **may** support lists of those primitive types, but this is subject to more investigation on how complex this would be to support.

The Admin UI would understand how to render inputs for the struct type, and individual fields could also have custom ui components defined just like regular custom fields.

**Comment by michaelbromley** [comment]
Notes on naming (one of the 2 hard things...)

- "**object**": I started using this because it is well-known and simple. But upon implementing the various types, I started to dislike it because "object" is such an overloaded term, so types like `ObjectCustomFieldConfig` and `ObjectFieldConfig` started to get confusing. I want something that is more distinct and recognizable as referring to the type of this new custom field.
- "**record**": This is a possibility - it fits exactly to the use-case (https://en.wikipedia.org/wiki/Record_(computer_science)). Also suffers a little from being very generic, but not as bad as "object"
- "**json**": I think everyone will know what is meant is we use this name, but I don't want to because it will then imply that we support all features of JSON, which we do not guarantee.
- "**structuredData**": It is distinctive and descriptive, but I think it is overly-long. `StructuredDataCustomFieldConfig` is just too much.
- "**struct**": I come back to this term. It is very distinctive (not used anywhere else in Vendure), it is synonymous with "record", and it is short.

If we look at "structs" in various programming languages, we see the pattern of structured data, just like the kind that we want to support with this feature:

C
```c
struct Person {
    char name[50];
    int age;
    float height;
};
```

c++
```cpp
struct Person {
    std::string name;
    int age;
    float height;

    void introduce() {
        std::cout << "Name: " << name << ", Age: " << age << ", Height: " << height << "\n";
    }
};
```

Go
```go
type Person struct {
    Name   string
    Age    int
    Height float64
}
```

Rust
```rust
struct Person {
    name: String,
    age: u8,
    height: f32,
}
```

I'm gonna stick with `struct`.

**Comment by jyling** [comment]
Hi, sorry if this has already been thought out before. I wonder if structured data would also work for nested structures.

Let's say I'm working on an event product in my app, where I may have some contacts in the events, which may contain their name, avatar, and some contact type that they use.
```typescript
// custom field of product
{
  "contacts": [
    {
      "name": "Ken",
      "avatar": "https://random.images.com",
      "contacts": [
        {
          "icon": "email",
          "content": "exmaple@example.com"
        },
        {
          "icon": "linkedin",
          "content": "exmaple@example.com"
        },
        {
          "icon": "whatsapp",
          "content": "exmaple@example.com"
        }
      ]
    },
    {
      "name": "Joshua",
      "avatar": "https://random.images.com",
      "contacts": [
        {
          "icon": "email",
          "content": "exmaple@example.com"
        },
        {
          "icon": "linkedin",
          "content": "exmaple@example.com"
        },
        {
          "icon": "whatsapp",
          "content": "exmaple@example.com"
        }
      ]
    }
  ]
}
```

so based on the sample implementation, I would assume the end result would look something like this ?
```typescript
{
  "customFields": {
    "Product": [
      {
        "name": "contacts",
        "type": "struct",
        "fields": [
          {
            "name": "name",
            "type": "string"
          },
          {
            "name": "avatar",
            "type": "string"
          },
          {
            "name": "methods",
            "type": "struct",
            "fields": [
              { "name": "icon", "type": "string" },
              { "name": "contact", "type": "string" }
            ]
          }
        ]
      }
    ]
  }
}
```

**Comment by michaelbromley** [comment]
@jyling as discussed on the livestream and further in Discord, we won't be implementing support for nested structs. Summary of the reasons:

- Significantly increased complexity of implementation both in backend and UI
- Likely to be abused and lead to hard-to-maintain plugin code

The second reason is the main one. Feedback from a member of the Directus CMS team confirms this - Directus has a similar feature and it is often used in a way that leads to issues.

If you find that you need nested data structures, the advice would be to define a custom entity for that.

**Comment by jyling** [comment]
> @jyling as discussed on the livestream and further in Discord, we won't be implementing support for nested structs. Summary of the reasons:
> 
> * Significantly increased complexity of implementation both in backend and UI
> * Likely to be abused and lead to hard-to-maintain plugin code
> 
> The second reason is the main one. Feedback from a member of the Directus CMS team confirms this - Directus has a similar feature and it is often used in a way that leads to issues.
> 
> If you find that you need nested data structures, the advice would be to define a custom entity for that.

Hi, thanks for the reminder on this. I forgot to update the comment after the livestream. The reason is sound.

By the way, since this feature essentially involves a JSON structure in the database, how should we handle migrations when there are changes to the structure of the custom fields? This might have already been mentioned during the livestream (I’ll check on that later), but I wanted to put this out here for discussion.

Also, I still think this is a very cool feature and would allow us to avoid doing some janky stuff when dealing with JSON in the custom field 🔥 🔥 🔥

**Comment by michaelbromley** [comment]
> By the way, since this feature essentially involves a JSON structure in the database, how should we handle migrations when there are changes to the structure of the custom fields?

There is no built-in mechanism for this, but I believe this would be possible with the native json operators of postgres/mysql. For SQLite I think you'd need a JS script to do it, I'm not sure if you can manipulate json directly in SQL there.
