### ISSUE TITLE
404 for docs search results

### ISSUE THREAD

**Issue by martijnvdbrug** [vendure-ecommerce/vendure#2957]
**Describe the bug**
There are quite a few search results that lead to a 404 page.

**To Reproduce**
1. Go to https://docs.vendure.io/
2. Search for "Draft"
3. Click the top result, it will lead you to `https://docs.vendure.io/user-guide/orders/draft-orders/`, which doesn't exists

I've come across quite a few of these, most of them in `usser/-guide`. I didn't keep track of all of them though...

![image](https://github.com/user-attachments/assets/49d0b73d-a52a-41a7-bab2-d5ba2c3d4fec)

**Expected behavior**
No 404's in the search results

**Comment by michaelbromley** [comment]
Ah good point. The "user guide" pages were not yet updated since we refreshed the Admin UI in v2. So that's long overdue. It looks like the Typesense scraper is picking them up from the sitemap.xml file.

Ultimate solution would be to actually update them and get them published.

For now there should be a way to exclude them from the scraping. The scraper config file is here: https://github.com/vendure-ecommerce/vendure/blob/3322a5633ea3215064a084d2c63993c22183812e/docs/scraper/config.json, and I think we could use the 
[stop_urls](https://docsearch.algolia.com/docs/legacy/config-file/#stop_urls-optional) option to exclude those pages.

**Comment by michaelbromley** [comment]
I restored the guides in this commit https://github.com/vendure-ecommerce/vendure/commit/2f2248c5ccf0f642425fb0cd985f4b5c5cb12905

They are still pretty sparse on info, but we can start improving them from here: https://docs.vendure.io/user-guide/
