### ISSUE TITLE
Mollie Plugin doesn't check for eligibility

### ISSUE THREAD

**Issue by martijnvdbrug** [vendure-ecommerce/vendure#2973]
**Is your feature request related to a problem? Please describe.**
The Mollie plugin should check if the Mollie payment method is eligible for the given order, before creating a payment intent. Currently, Vendure will throw an Ineligible Payment Method error after payment, but funds have already been withdrawn from the clients account.

**Describe the solution you'd like**
The `createPaymentIntent()` in `mollie.service.ts` should check if the payment method is eligible, if not, throw an INELIGIBLE_PAYMENT_METHOD_ERROR

**Comment by casperiv0** [comment]
We've had this happen several times in production the last 2 weeks. The customer would apply a coupon code which would give them 70% discount, then they remove that coupon code and add another coupon code which makes their order free. We don't use Mollie for free orders, but the Mollie transaction did still continue.

Does the Mollie plugin support free orders, since we could switch that over already I think. That would avoid the bug I just mentioned, or not entirely? @martijnvdbrug

**Comment by martijnvdbrug** [comment]
@casperiv0 The latest version of the Mollie plugin contains a [pretty serious bug](https://github.com/vendure-ecommerce/vendure/issues/2941), and I am still in contact with Mollie support about it.

The latest version of the Mollie plugin supports $0 orders. In case of a $0 order, it just transitions the order to Settled, without ever calling Mollie. You should not use the latest version of the mollie plugin untill the above mentioned bug is fixed though.

**Comment by casperiv0** [comment]
I think that's the reason why my bug happens, I think they're somewhat correlated?

**Comment by martijnvdbrug** [comment]
@casperiv0 I've contacted you on Discord, because I'm not sure if this is related
