### ISSUE TITLE
How to contribute to Hub ?

### ISSUE THREAD

**Issue by meyvan** [vendure-ecommerce/vendure#2981]
**Describe the bug**
I used SES plugin  https://vendure.io/hub/aws-ses and found that the doc need to be updated to like below (FileBasedTemplateLoader)

```
..... EmailPlugin.init({

    templateLoader: new FileBasedTemplateLoader(path.join(__dirname, '../../static/email/templates')),
     .....
})

```

I was wondering how to contribute to update this hub page.

Could someone point me to this code please. Or is it because its the main site, its a private repo ?

**Comment by michaelbromley** [comment]
Hi,

That information on the Hub pages is not part of any open repo. Actually it is stored in the instance of Vendure that powers the Hub. So I'll update it, thanks for bringing it to our attention. Out of interest, does something not work with the current config, or is it just because that `templatePath` is marked as deprecated?

**Comment by meyvan** [comment]
Its because of marked as depreciated
