### ISSUE TITLE
createQueue doesn't immediately fully initialize it

### ISSUE THREAD

**Issue by hsensh** [vendure-ecommerce/vendure#3038]
**To Reproduce**
```
this.refreshConfigsQueue = await this.jobQueueService.createQueue({
      name: "refresh-configs",
      process: async (job) => {
        await this.fillVariables();
        return "success";
      },
    });

    setTimeout(() => {
      this.refreshConfigsQueue.add({});
    }, 1000)
```
This works

```
this.refreshConfigsQueue = await this.jobQueueService.createQueue({
      name: "refresh-configs",
      process: async (job) => {
        await this.fillVariables();
        return "success";
      },
    });

      this.refreshConfigsQueue.add({});
```

This doesn't
```
[server] TypeError: Cannot read properties of undefined (reading 'setRetries')
[server]     at BullMQJobQueueStrategy.add (/Users/hsensh/Documents/djlab/store/server/node_modules/.pnpm/@vendure+job-queue-plugin@3.0.1/node_modules/@vendure/job-queue-plugin/src/bullmq/bullmq-job-queue-strategy.ts:157:38)
[server]     at JobQueue.add (/Users/hsensh/Documents/djlab/store/server/node_modules/.pnpm/@vendure+core@3.1.0-next.0_patch_hash=ck7oyx2sxbu2pdya5g75awef5e_@types+express@4.17.21_encod_dccj7di4cwozivtphxmhga6o2m/node_modules/@vendure/core/src/job-queue/job-queue.ts:102:58)
```

**Environment (please complete the following information):**
 - @vendure/core version: 3.1.0
 - Nodejs version: 18
 - Database (mysql/postgres etc): mariadb

**Comment by michaelbromley** [comment]
Hi,

I think this is due to the order of [lifecycle hooks](https://docs.vendure.io/guides/developer-guide/plugins/#plugin-lifecycle).

NestJS lifecycle hooks go in this sequence:

1. onModuleInit
2. onApplicationBootstrap
3. onModuleDestroy
4. beforeApplicationShutdown
5. onApplicationShutdown

The JobQueueStrategy is initialized by the ConfigModule inside the `onApplicationBootstrap` hook. This means that if you attempt to add a job immediately inside the `onModuleInit` hook, the strategy has not yet initialized and in this case, the `options` object is not yet defined.

So this is not really a bug as such, more of a "gotcha". Try calling the `add()` method inside the `onApplicationBootstrap` hook in your plugin and see if that works.

**Comment by hsensh** [comment]
Worked! Thanks!
