### ISSUE TITLE
Stripe Plugin - Product variant stock level not updated in the ElasticSearch index after a successful transaction

### ISSUE THREAD

**Issue by LeftoversTodayAppAdmin** [vendure-ecommerce/vendure#3066]
**Describe the bug**
I am using ElasticSearch as the search backend and when I use Stripe Plugin to successfully complete a purchase, the search index for that product variant is not updated. As a result, the search results still have the inStock value set to true and shows an out of stock item in the search results. The products API shows the correct stock level immediately after the transaction and when the stock is allocated. 

**To Reproduce**

1. Use the Stripe Plugin to complete a purchase of a variant that has only 1 item in stock
2. Call the searchProducts API 
3. The product variant that just went out of stock still shows as inStock=true 

**Expected behavior**

- When an order is successfully processed and moved to Payment Settled state when items are allocated, it should also trigger a product variant reindex so the stock level in search is updated

**Environment (please complete the following information):**
 - @vendure/core version: 3.0.2
 - Nodejs version: 20
 - Database (mysql/postgres etc): MariaDB

**Additional context**
Looks like DefaultSearchPluginInitOptions has a parameter called indexStockStatus, what is a similar option for ElasticSearch or is it enabled by default? Also is it the responsibility of the Stripe plugin to trigger a reindex for each variant in the order?

![image](https://github.com/user-attachments/assets/b84c9e62-ae1d-452a-ab30-c2f85cb6f418)
![bug5](https://github.com/user-attachments/assets/e354e425-5976-457c-b2e7-2fa396b98a19)
![bug6](https://github.com/user-attachments/assets/62f673e2-8450-4741-a5f2-45fa59482e5e)
![bug7](https://github.com/user-attachments/assets/7109d652-78ec-4646-b438-7bffa9900c3f)

**Comment by michaelbromley** [comment]
Thanks for the report.

This should be a relatively straightforward one to solve. The problem is that currently neither the DefaultSearchPlugin nor the ElasticSearchPlugin are listening for the `StockMovementEvent`, which is the event that gets published whenever the stock level is being changed for a ProductVariant.

In the case of the DefaultSearchPlugin, the event subscribers are defined [here](https://github.com/vendure-ecommerce/vendure/blob/f4dadea020fa1093feab9d4575a5fd13c9c0f7c0/packages/core/src/plugin/default-search-plugin/default-search-plugin.ts#L115).

For the ElasticSearchPlugin they are defined [here](https://github.com/vendure-ecommerce/vendure/blob/b80ce1c155f120ed770b32afac0d15629ad3c555/packages/elasticsearch-plugin/src/plugin.ts#L278).

**Comment by LeftoversTodayAppAdmin** [comment]
So if I just add something like this, it should be enough to keep the product variant stock level up to date in ElasticSearch?

`
this.eventBus.ofType(StockMovementEvent).subscribe(event => {
            return this.elasticsearchIndexService.updateVariants(event.ctx, event.variants);
        });
`

**Comment by dlhck** [comment]
@LeftoversTodayAppAdmin yes, that seems like a good fix!

**Comment by LeftoversTodayAppAdmin** [comment]
Pull Request: https://github.com/vendure-ecommerce/vendure/pull/3112
