### ISSUE TITLE
RFC: Allow entity relations to be defined in CustomFields

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#308]
**Is your feature request related to a problem? Please describe.**
Currently CustomFields allow you to configure simple data types (string, boolean, number etc). Some features require adding relations to newly-defined entities to existing core entities. Example: adding a new `ProductReview` entity and wanting to implement a one-to-many relation with `Product`.

It _is_ possible to implement this right now, but not with CustomFields by first defining a ManyToOne relation on the ProductReview:

```ts
@Entity()
export class ProductReview  {
 
    @ManyToOne(type => Product)
    product: Product;

    @Column()
    rating: number;
}
```

and then extending the Product GraphQL type and adding a resolver to handle the new "reviews" property:

```ts
const apiExtensions = gql`
    extend type Product {
        reviews: [ProductReview!]!
    }
`;

@Resolver('Product')
export class ProductEntityResolver {
    constructor(@InjectConnection() private connection: Connection) {}

    @ResolveField()
    reviews(@Parent() product: Product) {
        return this.connection.getRepository(ProductReview).find({
            where: {
                product,
            },
        });
    }
}
```

This works but has the following limitations:

1. It is more complex than just defining a CustomField. CustomFields handle the extensions to the GraphQL API and resolvers automatically. This is a huge benefit in terms of developer experience.
2. There is no current way to define custom UI controls for non-custom fields. 

**Describe the solution you'd like**
The existing CustomFields definition API could be extended to allow the definition of relations, e.g:

```ts
const config = {
  // ...
  customFields: {
    Product: [
      {
        name: 'reviews',
        type: 'relation',
        relationType: 'oneToMany',
        relatedEntity: ProductReview,
      },
    ]
  }
};
```

The above config would then handle wiring up the relation with TypeORM, and extending the GraphQL API.

**Describe alternatives you've considered**
The alternative is to keep things as they are (as illustrated above). Despite being more verbose to implement, it is also more powerful - e.g. in the ProductReviews example, writing my own field resolver allows me to filter only "approved" reviews when dealing with the Shop API. Such custom logic would be difficult to support via the CustomFields API.

In terms of the second limitation (no ability to define custom controls in the admin ui), there could be a more general solution which allows one to override _any_ field in the UI. This would be a really nice feature to have in general, and is fairly likely to emerge at some point in the future.

**Request for comments**
This feature has been asked about a few times, so I created this issue to allow us to explore it. I'm currently undecided on whether to implement or not.

**Comment by option-greek** [comment]
Custom classes can also be explored to solve this problem using the classic inheritance model. They can define new fields and override methods to enhance the existing functionality. For example Custom class C expands on Product and replaces Product to handle any related functionality (the replacement part can be mentioned in the vendure config and instantiation can be done appropriately during run time (so kind of run time discovery and injection of types). This will give the flexibility of defining unrelated new classes to be used by any of these new custom classes (for example for Utilities and stuff like that) and let them define their own entity models as needed.

Advantages: 
1) More powerful functionality can easily be defined
2) Custom logic can be used to replace some of the standard logic

Disadvantages are: 
1) More coupled integration with vendure
2) Could be difficult to debug
3) Learning curve

**Comment by Zwergal** [comment]
This feature would be great as we exactly need that too. We want an admin user to be able to enter product reviews (1-n) for every product. And a review consists of a rating (int) and a review text (string).

We wouldn't mind if it is more code to write (The way it is possible now) as long as it is possible to add custom UI elements to the product details in the admin UI so an admin can enter data.

**Comment by michaelbromley** [comment]
@Zwergal It is definitely possible with the current setup, because I have already implemented a reviews plugin for my own project like this.

The way I did it was to create the new Review entity as described above, but the also add a "reviewRating" custom field to the Product entity which contains the average of all reviews for that product. Once you have a custom field, you can then create a custom UI component for your custom field which you can link to some custom UI route which displays all reviews for that product.

You can see a full working implementation of this idea here: https://github.com/vendure-ecommerce/real-world-vendure/tree/master/src/plugins/reviews

**Comment by Tyratox** [comment]
I've just implemented some entity relations in a plugin: https://github.com/Tyratox/vendure-product-recommendations and have taken the alternative approach described in this RFC.

The process seemed fine to me except for the admin ui part. There things got a little interesting especially as I haven't really worked with angular. I know of the possibility of a react app inside the admin ui (which is really really cool) but if you just want to add additional fields to say products it's more convenient to have it in the right place. What I've done is just use a boolean custom field which then renders additional fields if enabled.

https://raw.githubusercontent.com/Tyratox/vendure-product-recommendations/master/screenshot.png

Yes, the custom fields API probably isn't supposed to be used to add more than just a styled input field but it seems to work really nice. (I'm sorry for this hacky code)

Now there is just a boolean value for whether a given product has cross- or upselling relations and the frontend can then fetch them accordingly. Since you're able to define custom graphql endpoints and can issue them from angular components most things work fine. What might be a good idea is to add the ability to inject angular components into the product page without registering a custom field and an maybe easy way to retrieve the product id or the product variant id for these custom graphql queries?
By looking at vendure's code I realized the angular router can be used to [retrieve the product id ](https://github.com/Tyratox/vendure-product-recommendations/blob/master/src/ui-extensions/modules/product-recommendations-input.module.ts#L79) but except for a [really hacky workaround](https://github.com/Tyratox/vendure-bulk-discounts/blob/master/src/ui-extensions/modules/bulk-discount-input.module.ts#L94) I couldn't figure out a way to access product variant properties.

**Comment by michaelbromley** [comment]
@Tyratox valuable feedback, thanks! 

I think there may be a case for adding support in the ui-devkit for adding arbitrary custom components to detail pages, which would allow you to implement your plugin UI without needing the boolean value at all.

Also the idea of a "save" hook is good and would certainly be needed in that case.
