### ISSUE TITLE
ElasticSearchPlugin - Create new service to allow add only one new product to the index

### ISSUE THREAD

**Issue by rafapsm** [vendure-ecommerce/vendure#3090]
Hi @michaelbromley 

I’m using the Shop API to create new products, and I’m leveraging Elasticsearch to improve the performance of my application. I have the bufferedUpdates property set to true since I don’t need to update my index constantly. Instead, I call the search service’s reindex function whenever I create a new product.

The issue I’m facing is that the reindex function creates an entirely new index, whereas I only want to add a single new product. This is a problem because I have over 200k products, and recreating the whole index isn’t feasible.

Is there any possibility of creating a service to only add the new product to the index? 

Thanks!

**Comment by michaelbromley** [comment]
In this case you do not need to call reindex. Reindex has the sole purpose of completely rebuilding the search index and should be rarely needed.

When you have buffered updates enabled, rather than calling `reindex`, you can call `runPendingSearchIndexUpdates` ([docs](https://docs.vendure.io/reference/graphql-api/admin/mutations#runpendingsearchindexupdates)) which will run the buffered updates for _only_ those products that you have created.
