### ISSUE TITLE
Product code

### ISSUE THREAD

**Issue by radidas** [vendure-ecommerce/vendure#311]
It is worth adding a product code option, so that each product has its own code and there is a possibility to check who bought the product through this code and send a collective message to these people that, for example, there is a factory defect in this product.

**Comment by michaelbromley** [comment]
Currently each ProductVariant has an `sku`, which is a product code. Do you have something different in mind?

**Comment by radidas** [comment]
Yes, this SKU code is, I mean, if I have this product code, I physically have it, I would like to enter it in the Admin Panel to show me the people who bought this product and give me the opportunity to send them a message that, for example, this product has a manufacturing defect. Thank you .

**Comment by michaelbromley** [comment]
I see. I would recommend you create a dedicated plugin to achieve this - there are a few different aspects to consider:

* create a new GraphQL query which returns a list of customers who placed orders containing the given SKU
* implement the logic to power this (not too hard, a single DB query should be able to handle this)
* decide what channel to use for messages (I guess email) and decide how you want to do it. The simplest would be to generate a simple list e.g. csv and then use it in the email service of your choice to send the email. Or you could get fancy and implement a custom message-sending UI as a admin ui extension.

So the scope of this feature is quite large and variable, which is why I would not consider it for a core feature at this time.

I'll close this issue, but feel free to use Slack if you need specific help implementing this.
