### ISSUE TITLE
Dynamic registerCustomerAccount mutation

### ISSUE THREAD

**Issue by jonyw4** [vendure-ecommerce/vendure#388]
I added a few custom customer options in config but they are not in `registerCustomerAccount` mutation. 
I think that the mutation registerCustomerAccount  should be dynamic because Vendure have a feature to customize the Customer schema.

**Comment by jonyw4** [comment]
This is related to this issue #387

**Comment by oncode** [comment]
It would also be nice to have a way of setting the custom fields of an Order. 👍

**Comment by michaelbromley** [comment]
@oncode Do you mean setting Order custom fields via the Admin API & Admin UI?

**Comment by oncode** [comment]
@michaelbromley via the Admin API. I think there is currently no mutation where you can set the custom fields of the Order type. `setCustomerForOrder`, `setOrderShippingAddress`, `setOrderShippingMethod` or `addPaymentToOrder` have no CustomFields param. Maybe a new mutation (e.g. `setOrderCustomFields`) or a new param for all the order methods would be nice.

As example my use case: Currently I have an optional comment field at the end of the checkout and save it via the metadata param of `addPaymentToOrder`, because I can't save the comment in any mutation to the CustomField of the Order. There it would be nice to avoid another request and be able to save CustomFields with `addPaymentToOrder` for example, but maybe that's a bit weird as API design.

**Comment by michaelbromley** [comment]
@oncode Yep, that makes sense.

In the both the Shop & Admin API I think we'd want a separate mutation to modify the custom fields. I agree that tacking it on to `addPaymentToOrder` would be weird.

Would you mind opening a new issue for this so we can track it?

**Comment by oncode** [comment]
@michaelbromley Ah yes sry, actually meant Shop API, but Admin API would also make sense. Will add a new issue. 👍🏻
