### ISSUE TITLE
Email verification after password input

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#392]
A new feature where email is verified after adding password before letting the user continue to dashboard is requested

**Comment by michaelbromley** [comment]
To support this we could de-couple the "password" argument in the [registerCustomerInput](https://www.vendure.io/docs/graphql-api/shop/input-types/#registercustomerinput) from the `requireVerification` option.

Currently if `requireVerification = true`, then we throw an error when detecting a password in the registerCustomerInput. However, we could relax that and accept the password.

Later, when executing the [verifyCustomerAccount](https://www.vendure.io/docs/graphql-api/shop/mutations/#verifycustomeraccount) mutation, we check to see if that customer already set a password. If now, we require it (throw when none is passed). If a password is already set, we just mark that customer as verified and don't require a new password argument.

**Comment by michaelbromley** [comment]
I've spent a bit of time implementing this but then discovered a problem:

When `requireVerification` is `true`, this means that a Customer _cannot log in_ until the email address is verified. So trying to implement the idea above results in the following sequence:

1. Customer registers via `registerCustomerAccount` mutation, including their emailAddress and password.
2. We store the password hash **but** we cannot log then in at this point, because the email address has not been verified.
3. We send the verification email and that leads them to the `verifyCustomerAccount` mutation, which just sends the token automatically when they click the link in the email.
4. **problem** we can no longer authenticate them in the usual way now, because we don't have their password, since they did not enter it newly. We only have a hash of it.

### Solutions:

1. At step 4 above we could do a "special" authentication routine where we don't care about the password. We just authenticate without requiring it because we trust that this is the same person due to them having the valid verification token.
2. Or we could log them in at step 2 above, waiving the requirement for being verified for this case only.

Both solutions are viable, and both come with the drawback of complicating the auth flow with special cases. Special cases mean increased chances of security holes and oversights when refactoring etc.

**Comment by jonyw4** [comment]
I think that the whole point of using this method of auth its to be checking if the email is valid. So, if the token it's correct, we don't need to ask for the user to insert the password.

**Comment by jonyw4** [comment]
Recently I had to use the Amazon Cognito and they had implemented this feature in their authentication process. I separated some links from the docs just to complement the idea:

- https://docs.aws.amazon.com/cognito/latest/developerguide/signing-up-users-in-your-app.html
- https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-email-phone-verification.html

**Comment by michaelbromley** [comment]
OK I've implemented "solution 1" from the above comment, so that when a user verifies their email address, they get automatically authenticated too even when not providing a password.

Also added more docs on this in the GraphQL API docs (will be live on vendure.io after v0.14.0 release)
