### ISSUE TITLE
Add extra options in Promotions

### ISSUE THREAD

**Issue by jonyw4** [vendure-ecommerce/vendure#400]
I need some extra options in Promotion that I believe that could be an awesome addition of features to the promotions area in Vendure:

# New conditions:
## Filter by Region / Address
Add a condition based on address. So in that way it can create a promotion just for a region, country or city.

# New Actions
Add new actions based on these options:
- by product
- by shipping method
- by payment method

What do you think about it? I really want these features in vendure and I want to help with the PR.

**Comment by michaelbromley** [comment]
Yes, I agree we need to ship more promotion conditions & actions by default. Regarding your specific suggestions:

* By product: Yes, we need this. But we'll have to define a new `ConfigArgType` named `productIds` and also create a custom product picker component for the Admin UI. Quite a bit of work involved in that one.
* By shipping method: Can you explain how this one would work? An example promotion that requires this?
* By payment method: Same for this? I can't quite imagine the kind of promotion that this would support.

**Comment by jonyw4** [comment]
Okay, I will give some examples: 

## By Payment Method:

Suppose that I add two payment methods in Vendure: *Credit Card* and *Debit Card*, and on Black Friday I want to give 50% off in all products for every customer that uses **Debit Card as payment method**. 

## By Shipping Method:

Suppose that I two shipping methods in Vendure: *UPS* and *Correios*, and this weekend I want to create a promotion in my e-commerce and everyone that chooses UPS as shipping method will receive free shipping.

--- 

So this it's just some examples, I believe that it's really common in many e-commerce. To accomplish this we need to relate the Promotion to [ShippingMethod](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/entity/shipping-method/shipping-method.entity.ts) and [PaymentMethod](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/entity/payment-method/payment-method.entity.ts)

**Comment by michaelbromley** [comment]
The problem with the payment method-based promotion is that we only know the payment method at the point that `addPaymentToOrder` is executed, and at that point we cannot then change the price of the order. Such logic could be implemented by adding a `paymentMethod` custom field to the Order entity, and having the customer choose their payment method at an earlier stage in the checkout flow. Then you can apply a promotion action based on this. This is already possible as far as I can tell. 

Since it requires some custom fields and possibly custom mutations to set the custom field values, I would not include such a promotion condition with the core.

But to be honest I've never come across such a promotion before in real life. Perhaps it's just not common in this part of the world. What I _have_ seen is surcharges added to the order for certain payment methods. But that would be implemented as _additional_ charge rather than a discount. 

The shipping one should be possible to implement with a standard installation I think. You get the order object, look up the shipping method (if set) and then apply the discount based on that.

**Comment by jonyw4** [comment]
I did't knew that this limitation exists in Vendure, but i really think that the customer should have the ability to choose and change the paymentMethod before certain point in order. We can create another issue or maybe a discussion in Slack community. What do you think?
About the promotion its really common here in Brazil, all (small and big) e-commerce here have some discount based on payment method. I saw this in some places in USA too when i bought in Amazon and other e-commerces few years ago. So its really important to me to have this feature in Vendure.
About the promotion based on shipping method, how we can implement? I can make a PR to make this feature too

**Comment by jonyw4** [comment]
I took I time to study more about the documentation of Vendure and I realize that the _Payment Method_ its really different from _Shipping Method_. In the _Shipping Method_ we can combine and create a new shipping method based on a calculator, but in _payment method_ it's just an integration with a payment provider like `Braintree` or `Paypal`. So with that in mind, I think there it's not a proper way to add an new action based on payment method because that really depends on the provider that you are using. In this case, I think that the better way its to create a _Payment Method_ and a _Promotion Action_ based on the payment provider criteria.

**Comment by jonyw4** [comment]
But I think that we should have a native promotion action by shipping method. If you approve the idea, just tell me how I can do that I create a PR for it.

**Comment by michaelbromley** [comment]
Let's hold on this one for now. I think I need to slightly re-work the way that promotion actions & conditions relate to the Admin UI & how they are able to define new input types.

**Comment by jonyw4** [comment]
Okay, I'll be happy to help

**Comment by michaelbromley** [comment]
The work done on #414 (completed in the next branch) has opened up this issue and I'm now working on a few new promotion conditions/actions:

* Product-based
* Customer group based

On top of that I'll write a docs guide on creating your own. Then you'll be able to add your own and even PR them as a default if you think they are broadly applicable.
