### ISSUE TITLE
Allow uploadable "asset" as custom field

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#464]
**Is your feature request related to a problem? Please describe.**
We would like to have possiblity to have a custom field that would allow users of admin area upload custom asset (be it PDF, photo, or any other file).
E.g.:  would like to add custom field to Shipping method where I could upload logo of the provider that would be then displayed in Storefront when selecting one of eligible shipping method.

**Describe the solution you'd like**
New custom field "asset", when used in Admin UI there would be file uploader as its input, query this custom field could return any of the current props of "Asset".

**Describe alternatives you've considered**
Alternative is simple "string" field with url to a file previously uploaded somewhere, however that doesn't solve the missing "click to upload" feature.

**Comment by michaelbromley** [comment]
I agree we need this functionality. I'm not yet sure about the best implementation. 

Storing as a simple string (but with a seamless "click to upload" UI control) is the easiest way to do it, but it is somewhat fragile, since we are not really creating a relation in the DB between the custom field and the created Asset entity.

This brings us to #308, which discusses the ability to define entity relations in custom fields.
