### ISSUE TITLE
No valid channel was specified while testdrive

### ISSUE THREAD

**Issue by Uter1007** [vendure-ecommerce/vendure#48]
Hiho, I am just followed the readme (populated via yarn and then started server and admin-ui). When I try to login I will get: "No valid channel was specified". 

`{"errors":[{"message":"No valid channel was specified","locations":[{"line":2,"column":3}],"path":["config"],"extensions":{"code":"NO_VALID_CHANNEL","exception":{"stacktrace":["Error: error.no-valid-channel-specified","    at RequestContextService.getChannelToken (/home/uter/src/vendure/server/src/api/common/request-context.service.ts:59:19)","    at RequestContextService.fromRequest (/home/uter/src/vendure/server/src/api/common/request-context.service.ts:33:35)","    at AuthGuard.canActivate (/home/uter/src/vendure/server/src/api/middleware/auth-guard.ts:40:65)","    at process._tickCallback (internal/process/next_tick.js:68:7)"]}}}],"data":null}
`
Cheers,
Christoph

**Comment by michaelbromley** [comment]
Hi there!

Ah yes, I missed this out of the readme - I'll add it. Basically, since Vendure allows multiple channels, the current channel needs to be specified as a HTTP header, `vendure-token`. The value would correspond to the `defaultChannelToken` config option, so by default would be "default-channel".
