### ISSUE TITLE
Administrator is not allowed to view customer details, unable to login after error occured

### ISSUE THREAD

**Issue by martijnvdbrug** [vendure-ecommerce/vendure#555]
**Describe the bug**
As an administrator I am not allowed to view customer details. Clicking on a customer in 'customers', I am logged out with the message `You are not currently authorized to access "countries". Either you lack permissions, or your session has expired.`. After this I cannot log back in anymore with this account.

**To Reproduce**
0. Create a user with the following permissions for **1 specific channel**: 
![image](https://user-images.githubusercontent.com/6604455/99251027-f2040380-280c-11eb-9afc-36180f76e48c.png)

1. Go to 'customers'
2. Click on 'edit' for one of the customers
4. You are being logged out with error `You are not currently authorized to access "countries". Either you lack permissions, or your session has expired.`
5. After this you are unable to log back in

**Expected behavior**
The administrator of a channel should have permissions to view customers of his own channel.

**Environment (please complete the following information):**
 - @vendure/core version: 0.16.3
 - Nodejs version 12
 - Database (mysql/postgres etc): MySQL

**Comment by michaelbromley** [comment]
The CustomerDetail view attempts to fetch the list of available Countries for the address form. If the current user does not have read permissions on Settings, then this error results.

> After this I cannot log back in anymore with this account

I guess this is because upon successful login, the Admin UI attempts to redirect the the last route you were on. If you remove the query string from the URL this should not occur.

But the proper solution is to grant ReadSettings permissions on the Role.

**Comment by martijnvdbrug** [comment]
Is the redirect stored somewhere else that in the url? Even when removing the redirect and going straight to `/admin` logs me out with the same error.

I have granted read-permissions to Settings and this indeed works. Downside is that a channel admin can now settings from other channels

**Comment by michaelbromley** [comment]
> Is the redirect stored somewhere else that in the url?

No, here's the code that handles the redirect: https://github.com/vendure-ecommerce/vendure/blob/33be882c37ebe9e4c92f270b7431438fef0786a7/packages/admin-ui/src/lib/login/src/components/login/login.component.ts#L35-L51

It only checks `window.location.search`.

Re permissions for multi-tenant use-case: I see the problem here with granting read on Settings, with the current way the UI handles it. I'd suggest you open a separate issue for this. I do have an idea of allowing the developer to completely customize the left-hand nav menu in the Admin UI, so this would be one way to solve it. The channel admins could still use the API to fetch global settings data of course (which I guess is very unlikely for the average user), but at least then you'd be able to control what they are presented with in the UI.

**Comment by martijnvdbrug** [comment]
I cannot reproduce the issue: When removing the redirect form URL, I can login again. As far as I'm concerned this issue can be closed.
