### ISSUE TITLE
User softDelete while customer is registered in other channels

### ISSUE THREAD

**Issue by diegonc** [vendure-ecommerce/vendure#586]
Hello, what if the customer is registered in several channels? Shouldn't the line below be executed only if there are no channels left?

https://github.com/vendure-ecommerce/vendure/blob/adaa50d79668a932efb522c047d6390390482dac/packages/core/src/service/services/customer.service.ts#L635

Also, the customer update doesn't seem to pay attention to what channels the customer is associated with.

https://github.com/vendure-ecommerce/vendure/blob/adaa50d79668a932efb522c047d6390390482dac/packages/core/src/service/services/customer.service.ts#L633

Since a create operation is used to add customers to channels a delete operation seems to be the natural way of removing customers from channels.

**Comment by michaelbromley** [comment]
Hi,

Thanks for the report. 

> Also, the customer update doesn't seem to pay attention to what channels the customer is associated with.

What aspect of the update should pay attention to channels?

I agree that it makes sense for `delete()` to remove from the current channel and only do soft deletion if there is only 1 channel left.

**Comment by diegonc** [comment]
> What aspect of the update should pay attention to channels?

I meant that the deletedAt is set for all the channels unlike the find a few lines before that uses the channel id to load the customer:

```javascript
const customer = await this.connection.getEntityOrThrow(ctx, Customer, customerId, {
    channelId: ctx.channelId,
});
```

**Comment by michaelbromley** [comment]
Ah I see, thanks for clarifying. There is no way to set "deletedAt" for a specific Channel, since it is a property of the Customer entity itself. The equivalent to what you are implying would be to remove the relation between the Customer and that Channel, which effectively "deletes" the customer from that channel.

**Comment by martijnvdbrug** [comment]
Hi, thanks for your report.!

The GraphQL mutation `deleteCustomers` mutation works as expected: deleting in 1 channel removes the customer from that channel, but doesn't actually delete it.

I would say the `this.userService.softDelete(ctx, customer.user!.id);` also works as expected, since this soft deletes the user entity, regardless of the channels the user is in. 

The `softDelete` function is an internal API exposed by the service, and I think it's fair to assume that the user of this function understands that this function soft deletes the entity, even when that is shared between multiple channels.
(For end users this would be different, but that's why the GraphQL mutation behaves different).
