### ISSUE TITLE
[Admin API] - updateCustomer - Error

### ISSUE THREAD

**Issue by matigastirami** [vendure-ecommerce/vendure#590]
There is an error when you try to update a customer. I'll let the request and response example below:
`
mutation {
  updateCustomer(
    input: {
      firstName: "test"
      lastName: "test"
      phoneNumber: "1234567890"
      emailAddress: "blabla@blabla.com"
      id: "134",
      title: "sr"
    }
  ){
    ... on Customer{
      id
    },
    ... on ErrorResult{
      errorCode,
      message
    }
  }
}
`

Response:
`{"errors":[{"message":"i.hasOwnProperty is not a function","locations":[{"line":3,"column":17}],"path":["updateCustomer"]}],"data":null}`

**Comment by michaelbromley** [comment]
Thanks for the report, I can reproduce this.

Tracked it down to the fact that the graphql-js lib creates input arg objects with null prototypes (see https://github.com/graphql/graphql-js/pull/504). The fix is to replace this line: https://github.com/vendure-ecommerce/vendure/blob/adaa50d79668a932efb522c047d6390390482dac/packages/core/src/service/services/customer.service.ts#L242

with
```ts
Object.hasOwnProperty.call(i, 'emailAddress');
```

Will fix for the next release.

**Comment by matigastirami** [comment]
Thank you for your quick response @michaelbromley
