### ISSUE TITLE
Duplicate existing Product

### ISSUE THREAD

**Issue by oncode** [vendure-ecommerce/vendure#627]
**Is your feature request related to a problem? Please describe.**
When adding a product which is similar to existing ones, I often open a product in another tab while creating a new one, so I don't forget to add the same kind of facets. 

<img width="555" alt="Bildschirmfoto 2021-01-08 um 13 09 53" src="https://user-images.githubusercontent.com/2519814/104013603-f8ca4980-51b1-11eb-9587-9fb02480b7d9.png">

**Describe the solution you'd like**
It would be cool if product facets could be taken from an existing product.

**Describe alternatives you've considered**
Maybe this problem is to specific and writing my own plugin would be better. Or a more general solution, like the ability to duplicate a product as whole.

**Comment by michaelbromley** [comment]
I think "duplicate product" is probably something I'll include as standard. Maybe we can have an API where you can choose which properties of the current product to duplicate. Thus for your case you could check the "facets" and leave the rest as default (empty).

**Comment by oncode** [comment]
Yes, that sounds awesome! If you want you can close this request, if you have it already on your agenda.

**Comment by chladog** [comment]
If anyone in need of this right now, here's simple plugin that allows to duplicate product and product variant with all data:
https://github.com/chladog/vendure-duplicator

**Comment by floze** [comment]
+1 for this feature, I would find it very important.

**Comment by michaelbromley** [comment]
Ideally I would like to be able to offer a generic "duplicate" mutation that is potentially capable of duplicating _any_ entity.

Something like this:

### GraphQL API

```gql

input DuplicateEntityInput {
  entityName: String!
  entityId: ID!
}

type DuplicateEntitySuccess {
  newEntityId: ID!
}

type DuplicateEntityError implements ErrorResult {
    errorCode: ErrorCode!
    message: String!
    duplicationError: String!
}

union DuplicateEntityResult = DuplicateEntitySuccess  | DuplicateEntityError

extend type Mutation {
  duplicateEntity(input: DuplicateEntityInput!): DuplicateEntityResult
}
```

### Server Implementation

Then we need to have a way to provide the actual logic used when duplicating a particular entity. To make this able to also be able to handle custom entities too, we could add a new config option like this:

```ts
interface VendureConfig {
  // ...
  entityOptions: {
    entityDuplicationStrategy: EntityDuplicationStrategy[];
  }
}

interface EntityDuplicationStrategy extends InjectableStrategy {
  canDuplicate(entityName: string): boolean;
  duplicate(ctx: RequestContext, entityName: string, id: ID): Promise<VendureEntity>;
}
```

this allows us to provide any number of strategies for handling the duplication of given entities. A single strategy for e.g. `Product` could look like this:

```ts
export class ProductDuplicationStrategy implements EntityDuplicationStrategy {
  private connection: TransactionalConnection;

  init(injector: Injector) {
    this.connection = injector.get(TransactionalConnection);
  }

  canDuplicate(entityName: string) {
    return entityName === 'Product';
  }

  async duplicate(ctx: RequestContext, entityName: string, id: ID) {
    const product = await this.connection.getEntityOrThrow(ctx, Product, id);
   
    // specific logic to duplicate the product omitted;

    return newProduct;
  }
}
```

### Permissions

We'd need to make sure to restrict the `duplicateEntity` mutation to users with "update" permissions on the given entity. It's not clear yet how to implement that, but perhaps we can add to the strategy interface a way to specify permissions required to carry out the operation.

### Configurable duplication

In my [comment above](https://github.com/vendure-ecommerce/vendure/issues/627#issuecomment-756726792) I talk about the idea of being able to select which properties of an entity to duplicate. Supporting this in a generic way would introduce quite a bit of complexity, but it is worth considering how it might be supported. Or perhaps allowing a strategy to define a set of options that it is then free to interpret during the duplication process, which could be used to allow selective duplication, or even allow other types of sophisticated duplication.

### Admin UI

We'd then want some UI controls that allow the admin to duplicate an entity. This could be done from either

- the detail view
- the list view

I personally think it makes the most sense from the list view, but we'd need to keep in mind what happens if a user has multiple entities selected. Maybe we make the mutation input accept an array of IDs, and on the server we just call the strategy `duplicate` method multiple times, once for each ID.

### Default strategies

Then Vendure would ship with a set of strategies to handle duplication of the most common entities. We can add to these over time to increase coverage, but initially I would consider (in order of importance):

- Product
- ProductVariant
- Collection
- Promotion
- Shipping Method
- Payment Method

**Comment by mschipperheyn** [comment]
I would suggest adding the option to copy-duplicate a product to a different channel. For us, it's not so much about duplicating a product as much as it is copying instead of referencing a product on another channel

**Comment by michaelbromley** [comment]
With the new API you'll be able to write a custom duplicator that will do exactly this, including having a widget where you can specify the target channel in the admin ui.

**Comment by martijnvdbrug** [comment]
Is this going to be in V2 already? Or only the backend? Or inlcuding admin Ui part?

**Comment by michaelbromley** [comment]
v2.2 yeah. It's in there already including the Admin UI part. You can test it quickly with `npx @vendure/create@next my-shop`

**Comment by mschipperheyn** [comment]
@michaelbromley Be aware that copying prices is missing from the copy function when you include variants. Consequently, all prices on a copied product variants are zero. Bug or Intentional?

**Comment by michaelbromley** [comment]
@mschipperheyn sounds like a bug, because I believe [this line](https://github.com/vendure-ecommerce/vendure/blob/f5e866ba51014d9242796c75cba1de86455208c0/packages/core/src/config/entity/entity-duplicators/product-duplicator.ts#L168) is supposed to take care of making sure a price gets created.
