### ISSUE TITLE
Unable to sort or filter by productVariant's price

### ISSUE THREAD

**Issue by kosciak9** [vendure-ecommerce/vendure#642]
**Describe the bug**
I'm writing a frontend for Vendure backed website. I was using `0.17` version from `@vendure/create` with stock items, on SQLite. For some reason I couldn't get it to work after PC reboot, so I have recreated repository using `create`. Now it's running version `0.18` and my previous queries don't work. I looked through Changelog and Blog but I don't see a direct or indirect tip that this should break.

**To Reproduce**
My query:
```graphql
query ProductsForCollection(
  $slug: String
  $filters: ProductVariantFilterParameter
  $sort: ProductVariantSortParameter
) {
  collection(slug: $slug) {
    name
    slug
    description
    productVariants(options: { filter: $filters, sort: $sort }) {
      items {
        product {
          name
          assets {
            name
            source
          }
          id
          slug
          description
        }
        price
      }
      totalItems
    }
  }
}
```

Example variables:
- when only `slug` is provided it works.
- when sort like below is provided it throws
```json
{"variables":{"slug":"electronics","filters":{},"sort":{"price":"ASC"}}}
```

**Expected behavior**
It should filter / sort properly I believe.

**Environment (please complete the following information):**
 - @vendure/core version: `0.18.1`
 - Nodejs version: `14.15.0`
 - Database (mysql/postgres etc): `SQLite`  

**Additional context**
Fanatastic work on the software. It's exactly how I would've thought it out, but probably couldn't build. :)

**Comment by michaelbromley** [comment]
Hi,

I tried this query in the current version (0.18.1) and the sort and filtering works. Can you please provide the response you get for the query above?

**Comment by kosciak9** [comment]
Sure.

Request as JSON:
```json
{
  "query": "query ProductsForCollection($slug: String, $filters: ProductVariantFilterParameter, $sort: ProductVariantSortParameter) {\n  collection(slug: $slug) {\n    name\n    slug\n    description\n    productVariants(options: {filter: $filters, sort: $sort}) {\n      items {\n        id\n        product {\n          name\n          assets {\n            name\n            source\n            __typename\n          }\n          id\n          slug\n          description\n          __typename\n        }\n        price\n        __typename\n      }\n      totalItems\n      __typename\n    }\n    __typename\n  }\n}\n",
  "operationName": "ProductsForCollection",
  "variables": {
    "slug": "electronics",
    "filters": {
      "price": {
        "lt": 7709
      }
    },
    "sort": {
      "name": "ASC"
    }
  }
}
```

Response as JSON:
```json
{
  "errors": [
    {
      "message": "error.invalid-filter-field",
      "locations": [
        {
          "line": 6,
          "column": 5
        }
      ],
      "path": [
        "collection",
        "productVariants"
      ],
      "extensions": {
        "code": "USER_INPUT_ERROR"
      }
    }
  ],
  "data": {
    "collection": null
  }
}
```

**Comment by michaelbromley** [comment]
The error message is telling you the exact issue:

> The sort field 'price' is invalid. Valid fields are: createdAt, updatedAt, deletedAt, enabled, sku, stockOnHand, stockAllocated, outOfStockThreshold, useGlobalOutOfStockThreshold, trackInventory, id, productId, featuredAsset, taxCategory, languageCode, name

**Comment by kosciak9** [comment]
I understand that you're unable to sort by price (that it's the reason it fails). I'm asking, why has that changed and is it intentional, because, well, removal of sorting / filtering by price sounds counter-intuitive for an e-commerce website.

**Comment by kosciak9** [comment]
I've looked through blog post and GitHub releases information and have not found that changing. Is that maybe related to mock data being out of date for 0.18 release?

**Comment by michaelbromley** [comment]
Got it. Hmm yeah there might be a regression here, I'll look into it!

**Comment by kosciak9** [comment]
Thanks, just began to work with your software, so not yet capable of researching bug on my own. Hopefully soon!

**Comment by michaelbromley** [comment]
I found the cause. The `ProductVariant.price` field was converted from a regular DB field to a "calculated" field in the 0.18 release. This prevents the auto-generated list query builder from knowing how to deal with sorting on this field.

It's a bit of a tough problem to solve, I'll need to get my thinking cap on... 🎓

**Comment by kosciak9** [comment]
Could you link related file(s)? Happy to brainstorm with you.

**Comment by michaelbromley** [comment]
All sorting & filtering queries are auto-generated by the [ListQueryBuilder class](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/service/helpers/list-query-builder/list-query-builder.ts).

This works by introspecting the TypeORM column metadata ([getColumnMetadata()](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/service/helpers/list-query-builder/get-column-metadata.ts)) and dynamically builds a query using the TypeORM QueryBuilder interface.

So the problem comes when we have e.g. the `price` field of ProductVariant: https://github.com/vendure-ecommerce/vendure/blob/ae07134185e53b557c88488b475c18c59eb39e35/packages/core/src/entity/product-variant/product-variant.entity.ts#L72-L78

This is a getter, calculated at run-time (this is necessary because the _actual_ price is channel-dependent and lives in another table, ProductVariantPrice).

So when introspecting TypeORM column metadata, there is no "price" column, hence the error.

Now, since those calculated fields can contain arbitrary JS logic to come up with the values, it's not possible to create some automatic way to know how to sort based on that field. E.g. with the ProductVariant.price, what we really need to do is JOIN the ProductVariantPrice table, and then sort based on the value of ProductVariantPrice.price.

So my current idea is to implement some way of defining the custom sorting/filtering logic associated with each calculated field (actually, only those calculated fields which return primitive values). This might be in the form of a function which returns parameters understood by the TypeORM QueryBuilder API. 

Then, the ListQueryBuilder can use that custom function when it needs to sort on that field. That's the high-level idea, the implementation will probably be quite difficult to get right. In some instances (e.g. the [Order.totalQuantity](https://github.com/vendure-ecommerce/vendure/blob/ae07134185e53b557c88488b475c18c59eb39e35/packages/core/src/entity/order/order.entity.ts#L148-L152) field) it will be _really_ challenging to implement I think.

Any other ideas welcome!

**Comment by kosciak9** [comment]
Thanks! Will try to dig in.

**Comment by michaelbromley** [comment]
I'm making some good progress with the approach outlined above.

Right now I have it so that in the `@Calculated()` decorator, you can define an SQL expression which will be used in sorting/filtering operations, and also allows for relation joins. Looks like this:

```TypeScript

    @Calculated({ expression: 'LENGTH(description)' })
    get descriptionLength() {
        return this.description.length || 0;
    }

    @Calculated({
        relations: ['prices'],
        expression: 'prices.price',
    })
    get price() {
        return this.activePrice;
    }
```
I've created some e2e tests and now I'm adding some more complex cases, including an e2e test sorting on Collection.productVariants.price.

Still need to figure out if we'll need to do anything special to make sure all supported DBs (mysql, postgres, SQLite) are handled.

**Comment by kosciak9** [comment]
As far as my very limited knowledge goes, it sounds reasonable if there are NoSQL databases that are supported.
