### ISSUE TITLE
User can have only single external authentication method, any new will unlink previous

### ISSUE THREAD

**Issue by s3m3n** [vendure-ecommerce/vendure#695]
There is a bug in `ExternalProvider` logic which unlinks all other authentication methods on user authentication when using `externalAuthenticationService.findCustomerUser()`.

In your [example strategy](https://www.vendure.io/docs/developer-guide/authentication/#backend) you do:

```
const user = await this.externalAuthenticationService.findCustomerUser(ctx, this.name, payload.sub);
    if (user) {
        return user;
    }
```

This method queries user with:

```
external-athentication.service.ts:90
return this.connection
            .getRepository(ctx, User)
            .createQueryBuilder('user')
            .leftJoinAndSelect('user.authenticationMethods', 'authMethod')
            .where('authMethod.strategy = :strategy', { strategy })
            .andWhere('authMethod.externalIdentifier = :externalIdentifier', { externalIdentifier })
            .andWhere('user.deletedAt IS NULL')
            .getOne();
```

Here you make a join on external methods with `where` statement on specific strategy. This method will always return single auth strategy for User.

After we return this user further from example Google strategy, Vendure AuthService calls `createAuthenticatedSessionForUser` which does:

```
auth.service.ts:92
user.lastLogin = new Date();
        await this.connection.getRepository(ctx, User).save(user, { reload: false });
```

It saves the user passed from strategy `authenticate` method which will always include SINGLE strategy, this is why TypeORM clears other authentication methods available for this user with this sweet update which unlinks all other methods for this user by setting userId to null:

```
Query: UPDATE `authentication_method` SET `userId` = ?, `updatedAt` = CURRENT_TIMESTAMP WHERE `id` = ? -- PARAMETERS: [null,18]
```

We hacked this for now by fetching all actual authentication methods before returning user from our strategy.

**Comment by michaelbromley** [comment]
I've been attempting to create a failing e2e test for this case but have been having trouble re-creating the scenario.

Let's say we have 2 external auth strategies: facebook, google.

1. Customer authenticates with facebook for the first time.  `findCustomerUser()` returns no match so we call `createCustomerAndUser()` and create a new User and Customer.
2. Same Customer later authenticates with google. The Customer's Google account returns the same email address as was used in the facebook strategy. Again, `findCustomerUser()` returns no match (because the "strategy" argument is different) so we call `createCustomerAndUser()` and create _another_ new User and Customer.

So at the end we have 2 Customers and 2 Users for the same person with a single email address. _This_ seems like a bug to me. I can't figure out a way using the ExternalAuthenticationService to end up with a User with multiple ExternalAuthenticationMethods.

Can you provide any more detail which could help me understand & reproduce this?

**Comment by s3m3n** [comment]
@michaelbromley sorry for late response.

 > So at the end we have 2 Customers and 2 Users for the same person with a single email address. This seems like a bug to me.
 
You are right this is the buggy behaviour in default flow with Google / Facebook examples. In our custom strategy we call `userService.getUserByEmailAddress` and take all `user.authenticationMethods` and then we add another one. So in our case there are multiple strategies possible while with G/FB examples there are none as Vendure will create more and more users with the same e-mail address. Should I update issue description?

**Comment by michaelbromley** [comment]
No that's fine, this comment is enough. I'll get both issues fixed.
