### ISSUE TITLE
Tax Line Calculation Strategy does not cover location based taxes, which are common/required in US

### ISSUE THREAD

**Issue by mattgills** [vendure-ecommerce/vendure#697]
**Is your feature request related to a problem? Please describe.**
Currently our team has implemented a custom plugin and mutation to trigger tax calculation, which calls an external API.  The primary down fall of this strategy is that we are required to manually calculate the order totals, and are unable to leverage the built in _private_ functions that handle the updating of these values. 

**Describe the solution you'd like**
We would like to have the ability to access the calculateOrderTotals method within the OrderCalculator OR have a new function that allows other services/plugins to request new order totals.  This would prevent us from having to duplicate code and make sure we are not missing any values in the totalization.

Alternatively, we could also see a use case for having the TaxLineCalculationStrategy being called when a user sets the shipping address for an order.  However, this is not triggered currently (as discussed below).

**Describe alternatives you've considered**
We have also considered using the new TaxLineCalculationStrategy, however, it is only called when products are added and removed from the cart.  Since taxes in the US are based on sku and location, the TaxLineCalculationStrategy is not called at the appropriate time.  By the time the user clicks the shipping address, the items have already been added.  Therefore, the tax call is not guaranteed to be triggered prior to checkout.

**Comment by michaelbromley** [comment]
Hi Matt,

This is definitely a use-case I want Vendure to support well. I'd like to understand a bit more about your current implementation. You mention having to manually calculate order totals. Does you calculation also take into account promotions? Or do you just assume that if a promotion is valid before tax, it is also valid after tax is applied?

It would be simple enough to make the `calculateOrderTotals` method public, but perhaps there is an even better possibility here. Like, a built-in trigger to re-calculate all taxes, similar to what your plugin does, but where you only need to define the specific logic relating to your case, rather than general totals calculation, which could get brittle if any internals change in the future.

If you are able to share any relevant code, that would help me understand the exact requirement better. If it needs to stay private feel free to DM over Slack.

**Comment by mattgills** [comment]
Hi Michael,

Our current implementation is a custom mutation named `setTaxForOrder`, which accepts an `orderId` as an input.  Within the resolver we carry out roughly the following:
```
// Query the order service for a fully populated order based on id
const order = await this.orderService.findOne(ctx, orderId);

// Make external API call
// The external service requires an address and will provide a tax rate for each sku
const taxResponse = await this.externalTaxService.getTaxForOrder(order);

for (const line of order.lines) {
      for (const item of line.activeItems) {
            item.taxLines = [
                {
                    description: <Some description>,
                    taxRate: <rate from external service for this sku>,
                },
          ]
          await this.connection.getRepository(ctx, OrderItem).save(item);
      }
}

// Calculate the order totals (copy of OrderService function)
// This needs to reworked and updated to the latest schema,
// which is already an indication that this practice is not sustainable
const orderTotals = calculateOrderTotals(order);
order.subTotal = orderTotals.totalPriceBeforeTax;
order.subTotalWithTax = orderTotals.totalPrice;

// Save the order, so the totals are in the DB
await this.connection.getRepository(ctx, Order).save(order);

return order;
```

Ultimately it's not the most complicated solution and I think it seems somewhat similar to `TaxLineCalculationStrategy`, except we do the full order at once instead of each line as it's added.  In the storefront, we call the custom `setTaxForOrder` mutation prior to the `ArrangingPayment` state (after the user selects their address).  Important note: we can also use this custom mutation to prevent the user from proceeding to `ArrangingPayment` if the tax service is down for some reason.

In addition to the above, I'd also like to point out that we recently implemented at custom surcharge, which has a nice interface through the OrderService.  As I dug deeper, that's when I realized there are many side effects and calculations triggered.  Therefore, I definitely agree that simply exposing the `calculateOrderTotals` function would not cover the full scope of adding a tax line.

**Comment by michaelbromley** [comment]
Thanks for all the extra detail. That's really useful.

Since you have what sounds like a workable solution for the time being, I'll probably get to this after the immediate breaking changes for v1.0 are done. I'd like to spend a bit more time on research and design of a general-purpose API for this and other similar use-cases.

**Comment by mattgills** [comment]
Sounds great, Michael.  Would you recommend just updating the `calculateOrderTotals` method to be consistent with the `OrderService` for the time being?

**Comment by michaelbromley** [comment]
Yes, copy and paste your way to success 😂 Just be sure to check the diffs on that method when performing upgrades until we have a stable solution.

**Comment by martijnvdbrug** [comment]
It seems the `taxlineCalculationStrategy.calculate()` is now called in `orderService.applyPriceAdjustments`, which is also called when an order's address is updated. Doesn't this solve the original use case (applying taxes based on SKU and location)?

Considering this, and the fact this issue is pretty, old, I will close this one. Feel free to create a new issue with the latest version of Vendure if this issue persists.
