### ISSUE TITLE
Allow for custom fields to have Rich text editor

### ISSUE THREAD

**Issue by vmatekole** [vendure-ecommerce/vendure#722]
We have a food store – each product has custom fields for allergens and ingredients. The text tends to be very long and requiring rich text. Allowing custom fields to have the rich text editor configurable is required here.

**Comment by michaelbromley** [comment]
Hi, have you taken a look at https://www.vendure.io/docs/plugins/extending-the-admin-ui/custom-field-controls/?

Using that approach, you should be able to use a rich text editor for your custom field. Though I agree it would be nice to make it easier to do. Relates to #415

**Comment by vmatekole** [comment]
@michaelbromley  Any response on this?

**Comment by michaelbromley** [comment]
Hi, sorry for the lack of response. Right now I have no plans to implement this - I am working on shipping the existing features as v1.0, but this is still something I'd like to have in a future release.

**Comment by michaelbromley** [comment]
Unfortunately I am going to defer this one for now, since there is a viable work-around (https://github.com/vendure-ecommerce/vendure/issues/722#issuecomment-784917395) already, and I don't yet have a solid handle on exactly what the ideal API should be for this yet (this is explored more in #415 but not yet set in stone).

One thing to note is that in v1.1.0 we introduced the "text" customField type, which will by default use a `<textarea>` input component.

**Comment by huseyinalp** [comment]
Hello @michaelbromley ;
Sometimes we need to have extra textarea or rich text input and it should be localizable. That is why I think that we need that...

Currently, I'm still using localeString input but at that way, it is not easy to manage data.

<img width="1174" alt="Screen Shot 2021-10-30 at 11 53 44" src="https://user-images.githubusercontent.com/86047365/139528405-fdeffcc5-5951-45c2-829d-b70d03a0a370.png">

Thanks

**Comment by michaelbromley** [comment]
@huseyinalp ah I see, you mean to have a multi-line input rather than a simple text imput. Yes, this will be possible once I finish #415, which I plan to do for the next minor release.
