### ISSUE TITLE
Pass data from PromotionCondition check() to PromotionAction execute()

### ISSUE THREAD

**Issue by karel-advantitge** [vendure-ecommerce/vendure#732]
**Is your feature request related to a problem? Please describe.**
Currently there is no continuity between the conditions and actions of Promotions. Because of this, in certain cases, we are required to repeat certain calculations and thus, pass some argument to both condition and action. Because of this, sometimes it's preferable to nog have a condition at all and to all checks and calculation in the action.

Example:
The store has a promotion: if you buy 3 sodas, you get a candy bar for free. The candy bar can be any of a list of candybars, with differing prices. This promotion can be cumulated, i.e. If you buy 6 sodas you get 2 candy bars and so on. If more candy bars are in the order, the most expensive one should be the one they get for free. This promotion should be applied to the individual items, not to the order.

Example current execution:
- ~~A PromotionCondition with arguments:~~
    - ~~a list of all sodas~~
    - ~~the required amount of sodas (3 in the case of tis example but we generalize the promotion)~~
- A PromotionItemAction with arguments:
    - a list of all sodas
    - the required amount of sodas (3 in the case of tis example but we generalize the promotion)
    - a list of all candy bars
    - the amount of free candy bars (1 in the case of tis example but we generalize the promotion)

The PromotionCondition can check if the order has the required amount of sodas by comparing with the list of sodas.
The PromotionItemAction can check if the current item is a candy bar by comparing with the list of candy bars. But it needs a list of all sodas as well, because it has to determine how many candy bars should be discounted and whether the current item is one of the candybars that should be discounted. This makes the PromotionCondition irrelevant. The 'condition check' done by the PromotionCondition has to be repeated by the PromotionItemAction anyway (for every item separately)

**Describe the solution you'd like**
Data could be passed from the conditions to the actions.
We could allow the check function of PromotionCondition to not just return a boolean, but also a state, let's say `PromotionConditionState` which is a json object containing calculated values. The test function on Promotion performs all check function in the way it does now, but it also accumulates all PromotionConditionStates in a key-value map where the key is the condition code, resulting in an object, let' say `PromotionState`, of type `{ [code: string]: PromotionConditionState }`.
This object can then be passed to the PromotionAction execute function in the Promotion apply function.
Looking at the code the `await promotion.test(ctx, order)` and `await promotion.apply(ctx, { order })` are always used close together. The test function could return the boolean it does now, as well as the PromotionState. The PromotionState object can then be passed to the apply function.

Example execution with solution:
- A PromotionCondition with arguments:
    - a list of all sodas
    - the required amount of sodas (3 in the case of tis example but we generalize the promotion)
    - a list of all candy bars
    - the amount of free candy bars (1 in the case of tis example but we generalize the promotion)
- A PromotionItemAction without arguments

The PromotionCondition checks the amount of sodas and calculates the amount of free candy bars. It compares the candy bars present in the order, determines which ones should be free and stores that in the state object.
The PromotionItemAction only has to check whether the current item is present in the state object.

**Comment by michaelbromley** [comment]
Thank you for the detailed proposal. I agree with your conclusion and suggested solution.

With this solution, we are effectively establishing a dependency relationship between PromotionAction and PromotionCondition. Let's think about how to deal with that dependency:

In your example, let's say the BuyXGetYFreeAction depends on the ContainsXAndYCondition. What happens when a Promotion is created in which we use the BuyXGetYFreeAction but fail to use the ContainsXAndYCondition?

1. The action can be written in such a way as to silently fail when the expected data dependency is not present.
2. There could be some explicit way to declare dependencies, which is enforced when one attempts to create or update a Promotion, e.g. a PromotionAction can optionally declare a list of dependencies in the form of PromotionCondition codes. 

The second option seems optimal for avoiding errors and unexpected behaviour. It also seems like it could be implemented in a non-breaking way. Perhaps we could even use it to strongly-type the `PromotionState` parameter that gets passed to the `execute()` function, which would make it clear at build-time when a dependency is required.

**Comment by karel-advantitge** [comment]
I agree that the second option is optimal. I'll get started on a PR
