### ISSUE TITLE
All jobs should be idempotent and have ability to be safely re-run.

### ISSUE THREAD

**Issue by vmatekole** [vendure-ecommerce/vendure#741]
Please see #739  for details!

**Comment by michaelbromley** [comment]
I'm not sure how we would ensure idempotence, since the actual work done by a job may be intrinsically not idempotent.

A good example is sending an email. The email will be sent (or at least attempted to be sent) for each run of the job.

But perhaps you mean it in the way that the _running of the job instance_ should be idempotent, disregarding the side-effects resulting from whatever work is to be done by the job.

In this case, this is achievable. The basic idea is to set the job's state back to "PENDING", at which point the worker should pick it up again and run it.

**Comment by vmatekole** [comment]
@michaelbromley  Agree... Even those jobs that are intrinsically not idempotent they can be in the sense that we can confirm that the job was successfully complete under certain conditions. In the case of an email — ensuring the job checks that email is sent with no errors and SMTP connection closed successfully would at least ensure that repeat emails are not sent.

**Comment by martijnvdbrug** [comment]
Since this is an old issue, and the comments indicate workaround exists, I will close this issue
