### ISSUE TITLE
Include price and priceWithTax convention for discounts

### ISSUE THREAD

**Issue by mattgills** [vendure-ecommerce/vendure#749]
**Is your feature request related to a problem? Please describe.**
Since every other item in an order has the option to see a price with and without tax, it would be great to have that convention extended to discounts.  Currently discounts only provide access to `amount`, which is the equivalent to `priceWithTax`.  In our shopping carts (and any shopping cart I've seen in the US), we display all items without tax.  The tax is displayed as a separate line item, which encompasses all tax for the order (see additional context section).  For discounts we are required to calculate the value without tax dynamically, which makes quite a few assumptions regarding the `taxLines` array.

**Describe the solution you'd like**
The primary solution I would like to see is the use of `price` and `priceWithTax` for discounts.

**Describe alternatives you've considered**
Our current alternative is to reverse calculate the price without tax using the taxLines.

**Additional context**
![image](https://user-images.githubusercontent.com/14302424/110155703-01a35a00-7db4-11eb-8a5d-3957a13c57a0.png)

**Comment by michaelbromley** [comment]
This is a good point and as well as being needed for you use-case would also make the API more consistent. 

The only problem is that it is a breaking change, since `amount` is currently _with tax_ and then would become _without tax_. I am trying to avoid breaking changes now that we are in the 1.0.0-beta phase. But on the other hand a relatively minor break, which would make such a difference to US-based projects is probably worthwhile.

**Comment by sidings** [comment]
Hi @michaelbromley, just adding onto this issue--here's a screenshot of another use case we've run into. We're trying to display to the user a list of the discounts that they've applied to their cart and the only way we can do that right now is to back calculate from the amount with tax, which ends up giving us rounding errors. Also, since the discount amount with tax changes every time the user modifies the cart, i.e adds or removes an item, the displayed discount amount (from the back calculation) also changes. We were hoping to avoid this by maybe adding another property to the `Cart` that would give us all the discounts as is instead of the discount with tax. 
![image](https://user-images.githubusercontent.com/17956982/111393652-87b28100-868f-11eb-8064-c5997590ffa8.png)

**Comment by mattgills** [comment]
Thank you for adding that screenshot as a strong example of the issue @sidings.  @michaelbromley For context, @sidings and I are on the same team and her follow up is directly related to my original request.  I appreciate that you are considering adding this into the beta phase, even though you want to avoid breaking changes.  Based on some recent stakeholder meetings, it seems increasingly important to have access to a reliable pre tax discount value.

**Comment by michaelbromley** [comment]
Thank you both for the additional information. I posed the question of whether to fix now or later in the Slack group and the response is a unanimous yes: 
![image](https://user-images.githubusercontent.com/6275952/111596575-9901a780-87cd-11eb-9df4-3c3a629997d3.png)

So I'll work on this for the next beta release.
