### ISSUE TITLE
has vendure a minimum required  eCommerce functionalities and features and is  trustable for a big project ?

### ISSUE THREAD

**Issue by loveyandex** [vendure-ecommerce/vendure#785]
is vendure's state in the condition of trusting such as shopify and bigcommerce and woocommece ?
what options are lack and what requirements are solved ??
can a business trust your data base and modeling

**Comment by michaelbromley** [comment]
> is vendure's state in the condition of trusting such as shopify and bigcommerce and woocommece ?

I refer you to the FAQ on the website: https://www.vendure.io/article/faq/#vendure-is-still-beta-can-i-use-it-in-production

![image](https://user-images.githubusercontent.com/6275952/112171116-df9f3980-8bf3-11eb-9490-8bb0047ac642.png)

> what options are lack and what requirements are solved ??

The landing page has a list:

![image](https://user-images.githubusercontent.com/6275952/112171463-212fe480-8bf4-11eb-93e7-fe338e6d280d.png)

> can a business trust your data base and modeling

Many businesses already do. Whether your business can and should is a matter for your developers to evaluate.

I will close this issue since it is neither a bug report nor feature request. If you'd like to discuss these issues further, feel free to start a thread in the [discussion forum](https://github.com/vendure-ecommerce/vendure/discussions)!
