### ISSUE TITLE
Query Collection(s) should return it's Products as well

### ISSUE THREAD

**Issue by Wanztwurst** [vendure-ecommerce/vendure#799]
The query for Collection(s) should return the assigned Products as well. Currently there are only ProductVariants present while Products belong to Collections as well.

Collection type currently:
```typescript
export type Collection = Node & {
  __typename?: 'Collection';
  id: Scalars['ID'];
  createdAt: Scalars['DateTime'];
  updatedAt: Scalars['DateTime'];
  languageCode?: Maybe<LanguageCode>;
  name: Scalars['String'];
  slug: Scalars['String'];
  breadcrumbs: Array<CollectionBreadcrumb>;
  position: Scalars['Int'];
  description: Scalars['String'];
  featuredAsset?: Maybe<Asset>;
  assets: Array<Asset>;
  parent?: Maybe<Collection>;
  children?: Maybe<Array<Collection>>;
  filters: Array<ConfigurableOperation>;
  translations: Array<CollectionTranslation>;
  productVariants: ProductVariantList;
  customFields?: Maybe<Scalars['JSON']>;
};
```

To add:
`products: Array<ProductList>` and associated types for querying.

A benefit would be to use the Collections as categories in the storefront, where the belonging products are listed as well without needing to query all products and filtering for the collectionId additionally. Also it would just make sense to have the connection represented on the api both ways.

The AdminUi could display the Collections' contents split into Products and ProductVariants (which are already shown) like this:
![Screenshot_20210330_153558](https://user-images.githubusercontent.com/16679007/112997825-bccdd180-916d-11eb-8c16-77af38aefeec.png)

**Comment by michaelbromley** [comment]
I agree that it would be useful to be able to access related Products from a Collection type. The problem is that there is no direct relationship between Collection <-> Product in the data model. Collections contain ProductVariants only. So to get the list of related Products we'd need to do a JOIN on `productVariant.product` and then de-duplicate the products.

If this were then to be used as the primary means to list collections in the storefront, then a possible significant perf penalty may be introduced as compared to using the `search` query.

* Listing the Products in a Collection via the `search` query = 1 table query
* Listing Products via the method described above = deep JOIN via collection x productVariant x product x productTranslation. So a collection with, e.g. 1000 variants distributed between 500 products  and multiple languages would result in an SQL query which potentially requires several orders of magnitude more memory & computation to process, as compared to the `search` query (which is pre-indexed and de-normalized in order to get around the need for multiple joins).

**Comment by Wanztwurst** [comment]
Couldn't this be preprocessed in the same job as the ProductVariant-Collection relations and saved to a new relations table?

**Comment by michaelbromley** [comment]
Yes, this is a possible solution. For now I would defer it to a future major release because I do not want to introduce any breaking DB schema changes at this point. 

Although IMO this is still inferior to using the `search` query for storefront category listings. The reason is that even with a direct Collection <-> Product relation, joins are still needed to fetch the Product name, and if you want to display any price information then you'll in any case need to join the ProductVariant & ProductVariantPrice tables.

**Comment by Wanztwurst** [comment]
Okay! Thank you for considering!
