### ISSUE TITLE
Language code of root collection translation always gets added with languageCode en 

### ISSUE THREAD

**Issue by claboran** [vendure-ecommerce/vendure#822]
**Description of the issue**
The first Collection in a pure none English language context does not appear in AdminUI.

**To Reproduce**
1. Start with a complete empty database
2. Create TAX Settings, Zone, Country and all required things from scratch (in my case DE)
3. Change settings of the default channel to DE
4. Remove English from Available Languages
5. Add Assets, Facets, etc.
6. Create your first Collection
7. The Collection could be added without problem but does not apear in AdminUI
8. Query database ```sql select * from collection_translation; ``` __root_collection__ has languageCode 'en'
9. Update the record for __root_collection__ to 'de'
10. Refresh AdminUI -> Collection shows up...

**Expected behavior**
Root collection should be created in the appropriate language context.

**Environment:**
 - @vendure/core version: 0.18.4
 - Nodejs version: 14.10.0
 - Database (mysql/postgres etc): postgres 12

**Comment by michaelbromley** [comment]
Thanks for the report. One question: have you changed the `VendureConfig.defaultLanguageCode` value in your config file?

The issue seems to stem from [this line](https://github.com/vendure-ecommerce/vendure/blob/76361d5165483dc8f4279976c073f6a8157ef10b/packages/core/src/service/services/collection.service.ts#L546) which is using that config value to determine the language of the root collection. The solution would be to instead use `ctx.languageCode`

**Comment by claboran** [comment]
@michaelbromley: Will check that, I did probably not change defaultLanguageCode.

**Comment by michaelbromley** [comment]
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, let me know and I'll re-open it.
