### ISSUE TITLE
Allow stockLevel to be Int

### ISSUE THREAD

**Issue by chladog** [vendure-ecommerce/vendure#901]
**Is your feature request related to a problem? Please describe.**
There are use cases where stockLevel needs to be actual number of stock instead of general string.
stockLevel property on ProductVariant should be able to be a number to avoid need of additional parsing.

This relates to:
1.) GraphQL return type
2.) StockDisplayStrategy return type

**Comment by michaelbromley** [comment]
I did consider this when designing the API, but the main problem is that a GraphQL field cannot be a union of scalar types, as in `stockLevel: String | Int`. To support a union of types we would need to wrap the data in a type, like:

```graphql
type StockLevelCount {
  value: Int!
}

type StockLevelStatus {
  value: String!
}

union StockLevel = StockLevelCount | StockLevelStatus
```

This would also complicate selecting the stock level, since you'd then need to use fragment spread syntax and figure out which of the union types was returned. All in all I thought that just returning a string, which is quite straightforward to parse to an int if needed, was prefereable.

An alternative would be to have a single object like:
```
type StockLevel {
  count: Int
  status: String
}
```

which would allow you to fill in either or both. But this also has issues with needing to check which one has a value.

**Comment by chladog** [comment]
Aah, wasn't aware of this problem. Nevermind! I think we can live with parsing the str it's the least effort ;-)
